r01lib: AFE_base Class Reference
AFE_base Class Reference abstract
#include <AFE_NXP.h>
Public Types
using raw_t = int32_t
using microvolt_t = double
using callback_fp_t = std::function<void(void)>
Public Member Functions
AFE_base (SPI &spi, bool spi_addr, bool highspeed_variant, int nINT, int DRDY, int SYN, int nRESET)
virtual ~AFE_base ()
virtual void begin (void)
virtual void boot (void)=0
virtual void reset (bool hardware_reset=false)=0
virtual void set_DRDY_callback (callback_fp_t fnc)
virtual void open_logical_channel (int ch, uint16_t cc0, uint16_t cc1, uint16_t cc2, uint16_t cc3)=0
virtual void open_logical_channel (int ch, const uint16_t(&cc)[4])=0
virtual void close_logical_channel (int ch)=0
virtual void close_logical_channel (void)=0
virtual void start (int ch)=0
virtual void start (void)=0
virtual void start_continuous_conversion (void)=0
virtual void DRDY_by_sequencer_done (bool flag=true)=0
virtual raw_t read (int ch)=0
virtual void read (raw_t *data_ptr)=0
virtual void read (std::vector< raw_t > &data_vctr)=0
virtual raw_t start_and_read (int ch)
virtual void start_and_read (raw_t *data_ptr)
virtual void start_and_read (std::vector< raw_t > &data_vctr)
double raw2uv (int ch, raw_t value)
double raw2mv (int ch, raw_t value)
double raw2v (int ch, raw_t value)
double coeff_mV (int ch)
double drdy_delay (int ch)
double drdy_delay (void)
int enabled_logical_channels (void)
void use_DRDY_trigger (bool use=true)
Public Member Functions inherited from SPI_for_AFE
SPI_for_AFE (SPI &spi, bool dev_ad)
virtual ~SPI_for_AFE ()
void txrx (uint8_t *data, int size)
void write_r16 (uint16_t reg)
void write_r16 (uint16_t reg, uint16_t val)
uint16_t read_r16 (uint16_t reg)
void write_r24 (uint16_t reg, uint32_t val)
int32_t read_r24 (uint16_t reg)
void burst (uint32_t *data, int length, int width=3)
Protected Member Functions
int bit_count (uint32_t value)
virtual void init (void)
void default_drdy_cb (void)
int wait_conversion_complete (double delay=-1.0)
Static Protected Member Functions
static void DRDY_cb (void)
Protected Attributes
bool highspeed_variant
InterruptIn pin_nINT
InterruptIn pin_DRDY
DigitalOut pin_SYN
DigitalOut pin_nRESET
int enabled_channels
double coeff_uV [16]
double ch_delay [16]
double total_delay
uint32_t drdy_count
volatile bool drdy_flag
Static Protected Attributes
static double delay_accuracy = 1.1
static constexpr uint32_t timeout_limit = 100000000
static callback_fp_t cbf_DRDY = nullptr
Detailed Description
Definition at line 57 of file AFE_NXP.h.
Member Typedef Documentation
callback_fp_t
using AFE_base::callback_fp_t = std::function<void(void)>
set callback function when DRDY comes
Definition at line 85 of file AFE_NXP.h.
microvolt_t
using AFE_base::microvolt_t = double
Definition at line 62 of file AFE_NXP.h.
raw_t
using AFE_base::raw_t = int32_t
ADC readout types
Definition at line 61 of file AFE_NXP.h.
Constructor & Destructor Documentation
AFE_base()
AFE_base::AFE_base (SPI & spi, bool spi_addr, bool highspeed_variant, int nINT, int DRDY, int SYN, int nRESET)
Constructor to create a AFE_base instance
Definition at line 21 of file AFE_NXP.cpp.
References enabled_channels, highspeed_variant, pin_DRDY, pin_nINT, pin_nRESET, pin_SYN, and SPI_for_AFE::SPI_for_AFE().
~AFE_base()
AFE_base::~AFE_base () virtual
Destractor
Definition at line 26 of file AFE_NXP.cpp.
Member Function Documentation
begin()
void AFE_base::begin (void) virtual
Begin the device operation
NAFE13388 initialization. It does following steps (1) Call reset() (2) Call boot()
Definition at line 38 of file AFE_NXP.cpp.
References boot(), init(), and reset().
bit_count()
int AFE_base::bit_count (uint32_t value) protected
Definition at line 97 of file AFE_NXP.cpp.
boot()
virtual void AFE_base::boot (void) pure virtual
Set system-level config registers
Implemented in NAFE13388_Base.
close_logical_channel() [1/2]
virtual void AFE_base::close_logical_channel (int ch) pure virtual
Logical channel disable
Parameters
ch logical channel number (0 ~ 15)
Implemented in NAFE13388_Base.
close_logical_channel() [2/2]
virtual void AFE_base::close_logical_channel (void) pure virtual
All logical channel disable
Implemented in NAFE13388_Base.
coeff_mV()
double AFE_base::coeff_mV (int ch) inline
Coefficient to convert from ADC read value to micro-volt
Parameters
ch logical channel number
Definition at line 219 of file AFE_NXP.h.
References coeff_uV.
default_drdy_cb()
void AFE_base::default_drdy_cb (void) protected
Definition at line 56 of file AFE_NXP.cpp.
References drdy_count, and drdy_flag.
DRDY_by_sequencer_done()
virtual void AFE_base::DRDY_by_sequencer_done (bool flag = true) pure virtual
DRDY event select
Parameters
set true for DRDY by sequencer is done
Implemented in NAFE13388_Base.
DRDY_cb()
void AFE_base::DRDY_cb (void) static protected
Definition at line 50 of file AFE_NXP.cpp.
References cbf_DRDY.
drdy_delay() [1/2]
double AFE_base::drdy_delay (int ch) inline
Caliculated delay from logical channel setting (for single channel)
Parameters
ch logical channel number
Definition at line 228 of file AFE_NXP.h.
References ch_delay.
drdy_delay() [2/2]
double AFE_base::drdy_delay (void) inline
Caliculated delay from logical channel setting (for all channels)
Definition at line 235 of file AFE_NXP.h.
References total_delay.
enabled_logical_channels()
int AFE_base::enabled_logical_channels (void) inline
Number of enabled logical channels
Definition at line 241 of file AFE_NXP.h.
References enabled_channels.
init()
void AFE_base::init (void) protected virtual
Definition at line 30 of file AFE_NXP.cpp.
References default_drdy_cb(), DRDY_cb(), drdy_flag, pin_DRDY, and set_DRDY_callback().
open_logical_channel() [1/2]
virtual void AFE_base::open_logical_channel (int ch, const uint16_t(&) cc[4]) pure virtual
Configure logical channel
Parameters
ch logical channel number (0 ~ 15)
cc array for CH_CONFIG0, CH_CONFIG1, CH_CONFIG2 and CH_CONFIG3 values
Implemented in NAFE13388_Base.
open_logical_channel() [2/2]
virtual void AFE_base::open_logical_channel (int ch, uint16_t cc0, uint16_t cc1, uint16_t cc2, uint16_t cc3) pure virtual
Configure logical channel
Parameters
ch logical channel number (0 ~ 15)
cc0 16bit value to be set CH_CONFIG0 register (0x20)
cc1 16bit value to be set CH_CONFIG1 register (0x21)
cc2 16bit value to be set CH_CONFIG2 register (0x22)
cc3 16bit value to be set CH_CONFIG3 register (0x23)
Implemented in NAFE13388_Base.
raw2mv()
double AFE_base::raw2mv (int ch, raw_t value) inline
Convert raw output to milli-volt
Parameters
ch logical channel number to select its gain coefficient
value ADC read value
Definition at line 200 of file AFE_NXP.h.
References coeff_uV.
raw2uv()
double AFE_base::raw2uv (int ch, raw_t value) inline
Convert raw output to micro-volt
Parameters
ch logical channel number to select its gain coefficient
value ADC read value
Definition at line 190 of file AFE_NXP.h.
References coeff_uV.
raw2v()
double AFE_base::raw2v (int ch, raw_t value) inline
Convert raw output to volt
Parameters
ch logical channel number to select its gain coefficient
value ADC read value
Definition at line 210 of file AFE_NXP.h.
References coeff_uV.
read() [1/3]
virtual raw_t AFE_base::read (int ch) pure virtual
Read ADC for single channel
Parameters
ch logical channel number (0 ~ 15)
Implemented in NAFE13388_Base.
read() [2/3]
virtual void AFE_base::read (raw_t * data_ptr) pure virtual
Read ADC for all channel
Parameters
data_ptr pointer to array to store ADC data
Implemented in NAFE13388_Base.
read() [3/3]
virtual void AFE_base::read (std::vector< raw_t > & data_vctr) pure virtual
Read ADC for all channel
Parameters
data_vctr vector object to store ADC data
Implemented in NAFE13388_Base.
References cbf_DRDY, delay_accuracy, and total_delay.
reset()
virtual void AFE_base::reset (bool hardware_reset = false) pure virtual
Issue RESET command
Implemented in NAFE13388_Base.
set_DRDY_callback()
void AFE_base::set_DRDY_callback (callback_fp_t fnc) virtual
Definition at line 45 of file AFE_NXP.cpp.
References cbf_DRDY.
start() [1/2]
virtual void AFE_base::start (int ch) pure virtual
Start ADC
Parameters
ch logical channel number (0 ~ 15)
Implemented in NAFE13388_Base.
start() [2/2]
virtual void AFE_base::start (void) pure virtual
Start ADC on all logical channel
Implemented in NAFE13388_Base.
start_and_read() [1/3]
int32_t AFE_base::start_and_read (int ch) virtual
Start and read ADC for single channel
Parameters
ch logical channel number (0 ~ 15)
Definition at line 62 of file AFE_NXP.cpp.
References cbf_DRDY, ch_delay, delay_accuracy, read(), start(), and wait_conversion_complete().
start_and_read() [2/3]
void AFE_base::start_and_read (raw_t * data_ptr) virtual
Start and read ADC for all channel
Parameters
data_ptr pointer to array to store ADC data
Definition at line 73 of file AFE_NXP.cpp.
References cbf_DRDY, delay_accuracy, read(), start(), total_delay, and wait_conversion_complete().
start_and_read() [3/3]
void AFE_base::start_and_read (std::vector< raw_t > & data_vctr) virtual
Start and read ADC for all channel
Parameters
data_vctr vector object to store ADC data
Definition at line 83 of file AFE_NXP.cpp.
References cbf_DRDY, delay_accuracy, read(), start(), total_delay, and wait_conversion_complete().
start_continuous_conversion()
virtual void AFE_base::start_continuous_conversion (void) pure virtual
Start continuous AD conversion
Implemented in NAFE13388_Base.
use_DRDY_trigger()
void AFE_base::use_DRDY_trigger (bool use = true)
Switch to use DRDY to start ADC result reading
Parameters
use true (default) to use DRDY. if false, caliculated delay is used to start reading.
Definition at line 133 of file AFE_NXP.cpp.
References default_drdy_cb(), and set_DRDY_callback().
wait_conversion_complete()
int AFE_base::wait_conversion_complete (double delay = -1.0) protected
Definition at line 110 of file AFE_NXP.cpp.
References delay_accuracy, drdy_flag, timeout_limit, and wait().
Member Data Documentation
cbf_DRDY
AFE_base::callback_fp_t AFE_base::cbf_DRDY = nullptr static protected
Definition at line 278 of file AFE_NXP.h.
ch_delay
double AFE_base::ch_delay[16] protected
Channel delay
Definition at line 268 of file AFE_NXP.h.
coeff_uV
double AFE_base::coeff_uV[16] protected
Coefficient to convert from ADC read value to micro-volt
Definition at line 265 of file AFE_NXP.h.
delay_accuracy
double AFE_base::delay_accuracy = 1.1 static protected
Definition at line 270 of file AFE_NXP.h.
drdy_count
uint32_t AFE_base::drdy_count protected
Definition at line 273 of file AFE_NXP.h.
drdy_flag
volatile bool AFE_base::drdy_flag protected
Definition at line 274 of file AFE_NXP.h.
enabled_channels
int AFE_base::enabled_channels protected
Number of enabled logical channels
Definition at line 262 of file AFE_NXP.h.
highspeed_variant
bool AFE_base::highspeed_variant protected
Definition at line 253 of file AFE_NXP.h.
pin_DRDY
InterruptIn AFE_base::pin_DRDY protected
Definition at line 255 of file AFE_NXP.h.
pin_nINT
InterruptIn AFE_base::pin_nINT protected
Definition at line 254 of file AFE_NXP.h.
pin_nRESET
DigitalOut AFE_base::pin_nRESET protected
Definition at line 257 of file AFE_NXP.h.
pin_SYN
DigitalOut AFE_base::pin_SYN protected
Definition at line 256 of file AFE_NXP.h.
timeout_limit
uint32_t AFE_base::timeout_limit = 100000000 static constexpr protected
Definition at line 276 of file AFE_NXP.h.
total_delay
double AFE_base::total_delay protected
Definition at line 269 of file AFE_NXP.h.
The documentation for this class was generated from the following files:
r01device/afe/AFE_NXP.h
r01device/afe/AFE_NXP.cpp