r01lib: Serial Class Reference
Serial Class Reference
Mbed-compatible UART class backed by interrupt-driven ring buffers.
#include <Serial.h>
Public Types
enum IrqType { RxIrq = 0 , TxIrq = 1 }
Interrupt source selector passed to attach().
Public Member Functions
Serial (int tx, int rx, int baud=115200)
Construct and initialise the Serial port.
virtual ~Serial ()
Destroy the Serial port and release hardware resources.
void baud (int baudrate)
Change the baud rate at runtime.
int putc (int c)
Write a single character to the TX ring buffer.
int getc (void)
Read one character.
int printf (const char *fmt,...)
Formatted print to the serial port.
bool readable (void)
Query whether at least one byte is available to read.
bool writable (void)
Query whether there is space in the TX ring buffer.
status_t write (const uint8_t *data, size_t length)
Write a byte array to the TX ring buffer.
status_t read (uint8_t *data, size_t length)
Blocking read of exactly length bytes.
void attach (func_ptr callback, IrqType type=RxIrq)
Register a callback for RX or TX interrupts.
void _irq_handler (void)
Internal: called from the global LPUART IRQ handler.
Public Member Functions inherited from Obj
Obj (bool done=false)
virtual ~Obj ()
Static Public Attributes
static constexpr size_t RX_RING_BUF_SIZE = 64U
static constexpr size_t TX_RING_BUF_SIZE = 256U
Private Member Functions
void resolve_pins (int tx, int rx)
void _setup_clock (void)
uint32_t _get_clk_freq (void)
void _release_reset (void)
void _register_instance (void)
void _unregister_instance (void)
void tx_enqueue (uint8_t b)
void update_irq_enables (void)
Private Attributes
LPUART_Type * _base
lpuart_config_t _config
uint32_t _clk_freq
uint32_t _instance
port_mux_t _mux
IRQn_Type _irqn
int _tx_pin
int _rx_pin
volatile uint8_t _rx_buf [RX_RING_BUF_SIZE]
volatile uint16_t _rx_head
volatile uint16_t _rx_tail
volatile uint8_t _tx_buf [TX_RING_BUF_SIZE]
volatile uint16_t _tx_head
volatile uint16_t _tx_tail
func_ptr _rx_callback
func_ptr _tx_callback
Detailed Description
Mbed-compatible UART class backed by interrupt-driven ring buffers.
Instantiate with a TX pin, RX pin, and optional baud rate. The constructor resolves the hardware peripheral, configures clocks, mux, and enables the LPUART. The destructor cleanly disables interrupts and de-initialises the peripheral.
Definition at line 70 of file Serial.h.
Member Enumeration Documentation
IrqType
enum Serial::IrqType
Interrupt source selector passed to attach().
Enumerator
RxIrq
Receive data register full.
TxIrq
Transmit data register empty (TX buffer drained).
Definition at line 76 of file Serial.h.
Constructor & Destructor Documentation
Serial()
Serial::Serial (int tx, int rx, int baud = 115200)
Construct and initialise the Serial port.
Resolves the tx / rx pin pair to the appropriate LPUART peripheral, configures the port mux, sets up clocks, releases reset, and calls LPUART_Init. Calls panic() if the pin combination is not supported on the current target.
Parameters
tx Transmit pin (e.g. USBTX, MB_TX).
rx Receive pin (e.g. USBRX, MB_RX).
baud Baud rate in bps (default 115200).
Definition at line 338 of file Serial.cpp.
References _base, _clk_freq, _config, _get_clk_freq(), _instance, _irqn, _mux, _register_instance(), _release_reset(), _rx_callback, _rx_head, _rx_pin, _rx_tail, _setup_clock(), _tx_callback, _tx_head, _tx_pin, _tx_tail, baud(), Obj::Obj(), panic(), DigitalInOut::pin_mux(), and resolve_pins().
~Serial()
Serial::~Serial () virtual
Destroy the Serial port and release hardware resources.
Disables RX/TX interrupts, disables the NVIC IRQ, calls LPUART_Deinit, and unregisters the instance from the IRQ dispatch table.
Definition at line 378 of file Serial.cpp.
References _base, _irqn, and _unregister_instance().
Member Function Documentation
_get_clk_freq()
uint32_t Serial::_get_clk_freq (void) private
_irq_handler()
void Serial::_irq_handler (void)
Internal: called from the global LPUART IRQ handler.
Not intended for direct use by application code.
Definition at line 442 of file Serial.cpp.
References _base, _rx_buf, _rx_callback, _rx_head, _rx_tail, _tx_buf, _tx_callback, _tx_head, _tx_tail, RX_RING_BUF_SIZE, and TX_RING_BUF_SIZE.
_register_instance()
void Serial::_register_instance (void) private
_release_reset()
void Serial::_release_reset (void) private
_setup_clock()
void Serial::_setup_clock (void) private
_unregister_instance()
void Serial::_unregister_instance (void) private
attach()
void Serial::attach (func_ptr callback, IrqType type = RxIrq)
Register a callback for RX or TX interrupts.
Attaching an RxIrq callback enables the LPUART receive interrupt and switches getc / readable to ring-buffer mode. Attaching a TxIrq callback stores a function that is called once the TX ring buffer has been fully drained.
Pass nullptr to remove a previously registered callback.
Parameters
callback Function to call on the selected interrupt event.
type RxIrq (default) or TxIrq.
Definition at line 429 of file Serial.cpp.
References _rx_callback, _tx_callback, RxIrq, and update_irq_enables().
baud()
void Serial::baud (int baudrate)
Change the baud rate at runtime.
Temporarily disables interrupts, re-initialises the peripheral, then restores interrupt enables according to the current callback state.
Parameters
baudrate New baud rate in bps.
Definition at line 484 of file Serial.cpp.
References _base, _clk_freq, _config, _tx_head, _tx_tail, and update_irq_enables().
getc()
int Serial::getc (void)
Read one character.
If an RX callback has been attached, reads from the RX ring buffer and returns -1 if no data is available. If no callback is attached, blocks until a byte is received via LPUART_ReadBlocking.
Returns
Received byte as int (0–255), or -1 if the ring buffer is empty and interrupt-driven mode is active.
Definition at line 506 of file Serial.cpp.
References _base, _rx_buf, _rx_callback, _rx_head, _rx_tail, and RX_RING_BUF_SIZE.
printf()
int Serial::printf (const char * fmt, ...)
Formatted print to the serial port.
Formats into a 256-byte stack buffer then enqueues each byte into the TX ring buffer.
Parameters
fmt printf-style format string.
... Variadic arguments matching fmt.
Returns
Number of characters written (same semantics as vsnprintf).
Definition at line 525 of file Serial.cpp.
References tx_enqueue().
putc()
int Serial::putc (int c)
Write a single character to the TX ring buffer.
Blocks (spin-waits) if the TX ring buffer is full.
Parameters
c Character to transmit (only the low 8 bits are used).
Returns
The character written, cast to int.
Definition at line 500 of file Serial.cpp.
References tx_enqueue().
read()
status_t Serial::read (uint8_t * data, size_t length)
Blocking read of exactly length bytes.
Delegates to LPUART_ReadBlocking; does not use the RX ring buffer.
Parameters
data Destination buffer.
length Number of bytes to read.
Returns
SDK status code from LPUART_ReadBlocking.
Definition at line 561 of file Serial.cpp.
References _base.
readable()
bool Serial::readable (void)
Query whether at least one byte is available to read.
Returns
true if data is available; false otherwise.
Definition at line 539 of file Serial.cpp.
References _base, _rx_callback, _rx_head, and _rx_tail.
resolve_pins()
void Serial::resolve_pins (int tx, int rx) private
tx_enqueue()
void Serial::tx_enqueue (uint8_t b) private
Definition at line 396 of file Serial.cpp.
References _base, _irqn, _tx_buf, _tx_head, _tx_tail, and TX_RING_BUF_SIZE.
update_irq_enables()
void Serial::update_irq_enables (void) private
Definition at line 410 of file Serial.cpp.
References _base, _irqn, _rx_callback, _tx_head, and _tx_tail.
writable()
bool Serial::writable (void)
Query whether there is space in the TX ring buffer.
Returns
true if at least one byte can be enqueued without blocking.
Definition at line 547 of file Serial.cpp.
References _tx_head, _tx_tail, and TX_RING_BUF_SIZE.
write()
status_t Serial::write (const uint8_t * data, size_t length)
Write a byte array to the TX ring buffer.
Enqueues all length bytes. Blocks on each byte if the TX ring buffer is momentarily full.
Parameters
data Pointer to the data to transmit.
length Number of bytes to transmit.
Returns
kStatus_Success.
Definition at line 553 of file Serial.cpp.
References tx_enqueue().
Member Data Documentation
_base
LPUART_Type* Serial::_base private
Definition at line 226 of file Serial.h.
_clk_freq
uint32_t Serial::_clk_freq private
Definition at line 228 of file Serial.h.
_config
lpuart_config_t Serial::_config private
Definition at line 227 of file Serial.h.
_instance
uint32_t Serial::_instance private
Definition at line 229 of file Serial.h.
_irqn
IRQn_Type Serial::_irqn private
Definition at line 231 of file Serial.h.
_mux
port_mux_t Serial::_mux private
Definition at line 230 of file Serial.h.
_rx_buf
volatile uint8_t Serial::_rx_buf[RX_RING_BUF_SIZE] private
Definition at line 248 of file Serial.h.
_rx_callback
func_ptr Serial::_rx_callback private
Definition at line 258 of file Serial.h.
_rx_head
volatile uint16_t Serial::_rx_head private
Definition at line 249 of file Serial.h.
_rx_pin
int Serial::_rx_pin private
Definition at line 233 of file Serial.h.
_rx_tail
volatile uint16_t Serial::_rx_tail private
Definition at line 250 of file Serial.h.
_tx_buf
volatile uint8_t Serial::_tx_buf[TX_RING_BUF_SIZE] private
Definition at line 253 of file Serial.h.
_tx_callback
func_ptr Serial::_tx_callback private
Definition at line 259 of file Serial.h.
_tx_head
volatile uint16_t Serial::_tx_head private
Definition at line 254 of file Serial.h.
_tx_pin
int Serial::_tx_pin private
Definition at line 232 of file Serial.h.
_tx_tail
volatile uint16_t Serial::_tx_tail private
Definition at line 255 of file Serial.h.
RX_RING_BUF_SIZE
size_t Serial::RX_RING_BUF_SIZE = 64U static constexpr
Size of the software receive ring buffer (bytes).
Definition at line 82 of file Serial.h.
TX_RING_BUF_SIZE
size_t Serial::TX_RING_BUF_SIZE = 256U static constexpr
Size of the software transmit ring buffer (bytes).
Definition at line 84 of file Serial.h.
The documentation for this class was generated from the following files:
r01lib/Serial.h
r01lib/Serial.cpp