r01lib: test_LM75B Class Reference
test_LM75B Class Reference
#include <test_LM75B.h>
Public Types
enum mode { COMPARATOR , INTERRUPT }
enum reg_num { Temp , Conf , Thyst , Tos }
Public Member Functions
test_LM75B (I2C &interface, const uint8_t i2c_address=(0x90 > > 1))
~test_LM75B ()
float read (void)
void thresholds (const float v0, const float v1)
void os_mode (const mode flag)
Public Member Functions inherited from I2C_device
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
virtual ~I2C_device ()
void repeated_start_enable (bool en=true)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
void write_r16 (uint8_t reg, uint16_t val)
uint8_t read_r8 (uint8_t reg)
uint16_t read_r16 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
bool ping (void)
uint8_t address (void)
void address_overwrite (uint8_t address)
virtual void ccc_set (CCC ccc, uint8_t data)
virtual uint8_t * ccc_get (CCC ccc, uint8_t *dp, uint8_t length)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Additional Inherited Members
Static Public Member Functions inherited from I2C_device
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t last=124)
Protected Attributes inherited from I2C_device
I2C & i2c
uint8_t i2c_addr
Detailed Description
test_LM75B class
test class for I2C_device
About LM75B: https://www.nxp.jp/products/sensors/ic-digital-temperature-sensors/digital-temperature-sensor-and-thermal-watchdog:LM75B
Definition at line 24 of file test_LM75B.h.
Member Enumeration Documentation
mode
enum test_LM75B::mode
Enumerator
COMPARATOR
Comparator mode
INTERRUPT
Interrupt mode
Definition at line 27 of file test_LM75B.h.
reg_num
enum test_LM75B::reg_num
Name of the PCT2075 registers
Enumerator
Temp
Temp register
Conf
Conf register
Thyst
Thyst register
Tos
Tos registe
Definition at line 33 of file test_LM75B.h.
Constructor & Destructor Documentation
test_LM75B()
test_LM75B::test_LM75B (I2C & interface, const uint8_t i2c_address = (0x90 >> 1))
Create a PCT2075 instance connected to specified I2C pins with specified address
Parameters
wire TwoWire instance
i2c_address I2C-bus address (default: (0x90>>1))
Definition at line 11 of file test_LM75B.cpp.
References I2C_device::I2C_device().
~test_LM75B()
test_LM75B::~test_LM75B ()
Destructor of PCT2075
Definition at line 15 of file test_LM75B.cpp.
Member Function Documentation
os_mode()
void test_LM75B::os_mode (const mode flag)
Set OS operation mode
Parameters
flag use PCT2075::COMPARATOR or PCT2075::INTERRUPT values
Definition at line 33 of file test_LM75B.cpp.
References Conf, I2C_device::read_r8(), and I2C_device::write_r8().
read()
float test_LM75B::read (void)
Get temperature value in degree Celsius [°C]
Returns
temperature value in degree Celsius [°C]
Definition at line 19 of file test_LM75B.cpp.
References I2C_device::read_r16(), and Temp.
thresholds()
void test_LM75B::thresholds (const float v0, const float v1)
Set Overtemperature shutdown threshold (Tos) and hysteresis (Thyst) in degree Celsius [°C]
This method takes 2 values and higher value will set as the threshold (Tos) and . another will be the hysteresis (Thyst)
Parameters
v0 a value in degree Celsius
v1 a value in degree Celsius
Definition at line 24 of file test_LM75B.cpp.
References Thyst, Tos, and I2C_device::write_r16().
The documentation for this class was generated from the following files:
r01device/test_LM75B.h
r01device/test_LM75B.cpp