r01lib: M24C02 Class Reference
M24C02 Class Reference
#include <M24C02.h>
Public Member Functions
M24C02 (I2C &wire, uint8_t i2c_address=(0xA0 > > 1))
virtual ~M24C02 ()
void begin (void)
int wait_write_complete (int n)
int write (int byte_adr, uint8_t data)
int write (int byte_adr, const uint8_t *dp, int length)
uint8_t read (int byte_adr)
int read (int byte_adr, uint8_t *dp, int length)
Public Member Functions inherited from I2C_device
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
virtual ~I2C_device ()
void repeated_start_enable (bool en=true)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
void write_r16 (uint8_t reg, uint16_t val)
uint8_t read_r8 (uint8_t reg)
uint16_t read_r16 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
bool ping (void)
uint8_t address (void)
void address_overwrite (uint8_t address)
virtual void ccc_set (CCC ccc, uint8_t data)
virtual uint8_t * ccc_get (CCC ccc, uint8_t *dp, uint8_t length)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Additional Inherited Members
Static Public Member Functions inherited from I2C_device
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t last=124)
Protected Attributes inherited from I2C_device
I2C & i2c
uint8_t i2c_addr
Detailed Description
M24C02 class
M24C02 class is a sample code for the PCA9846PW-ARD operation It demonstrates the switch operation with EEPROM on the shield board
Definition at line 22 of file M24C02.h.
Constructor & Destructor Documentation
M24C02()
M24C02::M24C02 (I2C & wire, uint8_t i2c_address = (0xA0 >> 1))
Create a M24C02 instance with specified address
Parameters
wire I2C instance
i2c_address I2C-bus address (default: (0xA0>>1))
Definition at line 9 of file M24C02.cpp.
References I2C_device::I2C_device().
~M24C02()
M24C02::~M24C02 () virtual
Definition at line 13 of file M24C02.cpp.
Member Function Documentation
begin()
void M24C02::begin (void)
Begin the device operation
This method turns-on the device
Definition at line 17 of file M24C02.cpp.
read() [1/2]
uint8_t M24C02::read (int byte_adr)
Read data
Parameters
byte_adr byte address
Returns
1 byte read data
Definition at line 72 of file M24C02.cpp.
References I2C_device::reg_r().
read() [2/2]
int M24C02::read (int byte_adr, uint8_t * dp, int length)
Definition at line 77 of file M24C02.cpp.
References PAGE_READ_SIZE, and I2C_device::reg_r().
wait_write_complete()
int M24C02::wait_write_complete (int n)
Wait write complete
Parameters
n loop count (in mili-second)
Returns
remain count: 0 means timeout
Definition at line 61 of file M24C02.cpp.
References I2C_device::ping(), and wait().
write() [1/2]
int M24C02::write (int byte_adr, const uint8_t * dp, int length)
Definition at line 34 of file M24C02.cpp.
References PAGE_WRITE_SIZE, I2C_device::reg_w(), and wait_write_complete().
write() [2/2]
int M24C02::write (int byte_adr, uint8_t data)
Write data
Parameters
byte_adr byte address
data 1 byte data for writing
Definition at line 21 of file M24C02.cpp.
References I2C_device::reg_w(), and wait_write_complete().
The documentation for this class was generated from the following files:
r01device/misc/eeprom/M24C02.h
r01device/misc/eeprom/M24C02.cpp