r01lib: LEDDriver Class Reference
LEDDriver Class Reference abstract
#include <LEDDriver.h>
Public Types
enum board { NONE , ARDUINO_SHIELD }
Public Member Functions
LEDDriver (uint8_t n_ch, uint8_t PWM_r, uint8_t oe)
virtual ~LEDDriver ()
virtual void reg_access (uint8_t reg, uint8_t val)=0
virtual void reg_access (uint8_t reg, uint8_t *vp, int len)=0
virtual uint8_t reg_access (uint8_t reg)=0
virtual void reg_access_r (uint8_t reg, uint8_t *vp, int len)=0
void pwm (uint8_t ch, float value)
void pwm (float *values)
void buffer_enable (bool flag)
void flush (void)
Public Attributes
const uint8_t n_channel
Protected Attributes
const uint8_t reg_PWM
const uint8_t oe_pin
Private Attributes
uint8_t * bp
Detailed Description
LEDDriver class
LEDDriver class is a base class for all LED drivers All actual device class will be derived from this class
Definition at line 40 of file LEDDriver.h.
Member Enumeration Documentation
board
enum LEDDriver::board
Enumerator
NONE
ARDUINO_SHIELD
Definition at line 43 of file LEDDriver.h.
Constructor & Destructor Documentation
LEDDriver()
LEDDriver::LEDDriver (uint8_t n_ch, uint8_t PWM_r, uint8_t oe)
Definition at line 11 of file LEDDriver.cpp.
References bp, n_channel, oe_pin, and reg_PWM.
~LEDDriver()
LEDDriver::~LEDDriver () virtual
Definition at line 16 of file LEDDriver.cpp.
References bp.
Member Function Documentation
buffer_enable()
void LEDDriver::buffer_enable (bool flag)
Buffer mode enable/Disble
Parameters
flag 'true' for enabling
Definition at line 53 of file LEDDriver.cpp.
References bp, and n_channel.
flush()
void LEDDriver::flush (void)
Flushing data
Send buffered PWM data to the LED driver
Definition at line 47 of file LEDDriver.cpp.
References bp, n_channel, reg_access(), and reg_PWM.
pwm() [1/2]
void LEDDriver::pwm (float * values)
Set PWM value for all channels
Parameters
*value Pointer to PWM value in float. Values should be in range from 0.0 to 1.0.
Definition at line 32 of file LEDDriver.cpp.
References bp, n_channel, reg_access(), and reg_PWM.
pwm() [2/2]
void LEDDriver::pwm (uint8_t ch, float value)
Set PWM value for a channel
Parameters
ch channel number
value PWM value in float. Values should be in range from 0.0 to 1.0.
Definition at line 22 of file LEDDriver.cpp.
References bp, reg_access(), and reg_PWM.
reg_access() [1/3]
virtual uint8_t LEDDriver::reg_access (uint8_t reg) pure virtual
Implemented in PCA995x_I2C, and PCA995x_SPI.
reg_access() [2/3]
virtual void LEDDriver::reg_access (uint8_t reg, uint8_t * vp, int len) pure virtual
Implemented in PCA995x_I2C, and PCA995x_SPI.
reg_access() [3/3]
virtual void LEDDriver::reg_access (uint8_t reg, uint8_t val) pure virtual
Implemented in PCA995x_I2C, and PCA995x_SPI.
reg_access_r()
virtual void LEDDriver::reg_access_r (uint8_t reg, uint8_t * vp, int len) pure virtual
Implemented in PCA995x_I2C, and PCA995x_SPI.
Member Data Documentation
bp
uint8_t* LEDDriver::bp private
Definition at line 86 of file LEDDriver.h.
n_channel
const uint8_t LEDDriver::n_channel
Definition at line 80 of file LEDDriver.h.
oe_pin
const uint8_t LEDDriver::oe_pin protected
Definition at line 84 of file LEDDriver.h.
reg_PWM
const uint8_t LEDDriver::reg_PWM protected
Definition at line 83 of file LEDDriver.h.
The documentation for this class was generated from the following files:
r01device/led/LEDDriver.h
r01device/led/LEDDriver.cpp