r01lib: PCA9846 Class Reference
PCA9846 Class Reference
#include <MUX_SW_NXP.h>
Public Types
enum channel { CH0 = 0x01 , CH1 = 0x02 , CH2 = 0x04 , CH3 = 0x08 }
Public Member Functions
PCA9846 (I2C &wire, uint8_t i2c_address=(0xE2 > > 1))
virtual ~PCA9846 ()
void begin (void)
void select (uint8_t flags)
uint8_t select (void)
Public Member Functions inherited from I2C_device
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
virtual ~I2C_device ()
void repeated_start_enable (bool en=true)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
void write_r16 (uint8_t reg, uint16_t val)
uint8_t read_r8 (uint8_t reg)
uint16_t read_r16 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
bool ping (void)
uint8_t address (void)
void address_overwrite (uint8_t address)
virtual void ccc_set (CCC ccc, uint8_t data)
virtual uint8_t * ccc_get (CCC ccc, uint8_t *dp, uint8_t length)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Static Public Attributes
static constexpr int N_CH = 4
Additional Inherited Members
Static Public Member Functions inherited from I2C_device
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t last=124)
Protected Attributes inherited from I2C_device
I2C & i2c
uint8_t i2c_addr
Detailed Description
PCA9846 class
PCA9846 class is a sample code for the PCA9846PW-ARD It demonstrates the switch operation with EEPROM on the shield board
Definition at line 22 of file MUX_SW_NXP.h.
Member Enumeration Documentation
channel
enum PCA9846::channel
Enumerator
CH0
CH1
CH2
CH3
Definition at line 25 of file MUX_SW_NXP.h.
Constructor & Destructor Documentation
PCA9846()
PCA9846::PCA9846 (I2C & wire, uint8_t i2c_address = (0xE2 >> 1))
Create a PCA9846 instance with specified address
Parameters
wire TwoWire instance
i2c_address I2C-bus address (default: (0xE2>>1))
Definition at line 11 of file MUX_SW_NXP.cpp.
References I2C_device::I2C_device().
~PCA9846()
PCA9846::~PCA9846 () virtual
Definition at line 15 of file MUX_SW_NXP.cpp.
Member Function Documentation
begin()
void PCA9846::begin (void)
Begin the device operation
This method turns-on the device
Definition at line 19 of file MUX_SW_NXP.cpp.
select() [1/2]
void PCA9846::select (uint8_t flags)
Channel select
Parameters
flags bitmap flags for enabling channels
Definition at line 23 of file MUX_SW_NXP.cpp.
References I2C_device::tx().
select() [2/2]
uint8_t PCA9846::select (void)
Channel select
Returns
flags bitmap flags for enabling channels
Definition at line 28 of file MUX_SW_NXP.cpp.
References I2C_device::rx().
Member Data Documentation
N_CH
int PCA9846::N_CH = 4 static constexpr
Number of channels
Definition at line 33 of file MUX_SW_NXP.h.
The documentation for this class was generated from the following files:
r01device/mux_sw/MUX_SW_NXP.h
r01device/mux_sw/MUX_SW_NXP.cpp