r01lib: PCF2131 Class Reference
PCF2131 Class Reference
#include <RTC_NXP.h>
Public Types
enum reg_num {
Control_1 , Control_2 , Control_3 , Control_4 ,
Control_5 , SR_Reset , _100th_Seconds , Seconds ,
Minutes , Hours , Days , Weekdays ,
Months , Years , Second_alarm , Minute_alarm ,
Hour_alarm , Day_alarm , Weekday_alarm , CLKOUT_ctl ,
Timestp_ctl1 , Sec_timestp1 , Min_timestp1 , Hour_timestp1 ,
Day_timestp1 , Mon_timestp1 , Year_timestp1 , Timestp_ctl2 ,
Sec_timestp2 , Min_timestp2 , Hour_timestp2 , Day_timestp2 ,
Mon_timestp2 , Year_timestp2 , Timestp_ctl3 , Sec_timestp3 ,
Min_timestp3 , Hour_timestp3 , Day_timestp3 , Mon_timestp3 ,
Year_timestp3 , Timestp_ctl4 , Sec_timestp4 , Min_timestp4 ,
Hour_timestp4 , Day_timestp4 , Mon_timestp4 , Year_timestp4 ,
Aging_offset , INT_A_MASK1 , INT_A_MASK2 , INT_B_MASK1 ,
INT_B_MASK2 , Watchdg_tim_ctl , Watchdg_tim_val
}
enum periodic_int_select { DISABLE , EVERY_SECOND , EVERY_MINUTE }
enum timestanp_setting { LAST , FIRST }
enum int_out_sel { INT_A , INT_B }
Public Types inherited from RTC_NXP
enum board { NONE , ARDUINO_SHIELD }
enum alarm_setting {
SECOND , MINUTE , HOUR , DAY ,
WEEKDAY
}
Public Member Functions
PCF2131 (I2C &interface, uint8_t i2c_address=(0xA6 > > 1))
PCF2131 (SPI &interface)
virtual ~PCF2131 ()
void begin (void)
bool oscillator_stop (void)
time_t rtc_time (void)
void set (struct tm *now_tm)
void alarm (alarm_setting digit, int val)
void alarm (alarm_setting digit, int val, int int_sel)
void alarm_clear (void)
void alarm_disable (void)
void timestamp (int num, timestanp_setting ts_setting, int int_sel=0)
time_t timestamp (int num)
uint8_t int_clear (void)
uint8_t int_clear (uint8_t *state_p)
void periodic_interrupt_enable (periodic_int_select sel, int int_sel=0)
Public Member Functions inherited from RTC_NXP
RTC_NXP ()
virtual ~RTC_NXP ()
time_t time (time_t *tp)
Private Attributes
const int int_mask_reg [2][2]
std::unique_ptr< Serial_device > intfp
Additional Inherited Members
Static Protected Member Functions inherited from RTC_NXP
static uint8_t bcd2dec (uint8_t v)
static uint8_t dec2bcd (uint8_t v)
Detailed Description
PCF2131 class
A base class for PCF2131 Implementing register operation with abstarcted interface
Definition at line 206 of file RTC_NXP.h.
Member Enumeration Documentation
int_out_sel
enum PCF2131::int_out_sel
Interrupt output selector
Enumerator
INT_A
INT_B
Definition at line 236 of file RTC_NXP.h.
periodic_int_select
enum PCF2131::periodic_int_select
Periodic interrupt selection descriptor
Enumerator
DISABLE
EVERY_SECOND
EVERY_MINUTE
Definition at line 225 of file RTC_NXP.h.
reg_num
enum PCF2131::reg_num
Name of the PCF2131 registers
Enumerator
Control_1
Control_2
Control_3
Control_4
Control_5
SR_Reset
_100th_Seconds
Seconds
Minutes
Hours
Days
Weekdays
Months
Years
Second_alarm
Minute_alarm
Hour_alarm
Day_alarm
Weekday_alarm
CLKOUT_ctl
Timestp_ctl1
Sec_timestp1
Min_timestp1
Hour_timestp1
Day_timestp1
Mon_timestp1
Year_timestp1
Timestp_ctl2
Sec_timestp2
Min_timestp2
Hour_timestp2
Day_timestp2
Mon_timestp2
Year_timestp2
Timestp_ctl3
Sec_timestp3
Min_timestp3
Hour_timestp3
Day_timestp3
Mon_timestp3
Year_timestp3
Timestp_ctl4
Sec_timestp4
Min_timestp4
Hour_timestp4
Day_timestp4
Mon_timestp4
Year_timestp4
Aging_offset
INT_A_MASK1
INT_A_MASK2
INT_B_MASK1
INT_B_MASK2
Watchdg_tim_ctl
Watchdg_tim_val
Definition at line 210 of file RTC_NXP.h.
timestanp_setting
enum PCF2131::timestanp_setting
Timestamp setting descriptor
Enumerator
LAST
FIRST
Definition at line 231 of file RTC_NXP.h.
Constructor & Destructor Documentation
PCF2131() [1/2]
PCF2131::PCF2131 (I2C & interface, uint8_t i2c_address = (0xA6 >> 1))
Create a PCF2131 instance connected to I2C with specified address
Parameters
interface I2C instance
i2c_address I2C-bus address (default: (0xBC>>1))
Definition at line 9 of file PCF2131.cpp.
References intfp.
PCF2131() [2/2]
PCF2131::PCF2131 (SPI & interface)
Create a PCF2131 instance connected to SPI
Parameters
interface SPI instance
Definition at line 14 of file PCF2131.cpp.
References intfp.
~PCF2131()
PCF2131::~PCF2131 () virtual
Destructor
Definition at line 19 of file PCF2131.cpp.
Member Function Documentation
alarm() [1/2]
void PCF2131::alarm (alarm_setting digit, int val) virtual
Alarm setting
Parameters
digit to specify which parameter to set: SECOND, MINUTE, HOUR, DAY, WEEKDAY in 'enum alarm_setting'
val Setting value. Set 0x80 to disabling
Implements RTC_NXP.
Definition at line 80 of file PCF2131.cpp.
References alarm().
alarm() [2/2]
void PCF2131::alarm (alarm_setting digit, int val, int int_sel)
Alarm setting
Parameters
digit to specify which parameter to set: SECOND, MINUTE, HOUR, DAY, WEEKDAY in 'enum alarm_setting'
val Setting value. Set 0x80 to disabling
int_sel Interrupt output selector.) for INT_A, 1 for INT_B
Definition at line 85 of file PCF2131.cpp.
References Control_2, RTC_NXP::dec2bcd(), int_mask_reg, intfp, and Second_alarm.
alarm_clear()
void PCF2131::alarm_clear (void) virtual
Alarm interrupt disable
Implements RTC_NXP.
Definition at line 93 of file PCF2131.cpp.
References Control_2, and intfp.
alarm_disable()
void PCF2131::alarm_disable (void) virtual
Interrupt clear
Implements RTC_NXP.
Definition at line 98 of file PCF2131.cpp.
References Control_2, and intfp.
begin()
void PCF2131::begin (void) virtual
Initializer Clears penginf interrupt
Implements RTC_NXP.
Definition at line 23 of file PCF2131.cpp.
References int_clear().
int_clear() [1/2]
uint8_t PCF2131::int_clear (uint8_t * state_p)
Interrupt clear
Definition at line 151 of file PCF2131.cpp.
References Control_2, Control_3, Control_4, and intfp.
int_clear() [2/2]
uint8_t PCF2131::int_clear (void) virtual
Interrupt clear
Implements RTC_NXP.
Definition at line 143 of file PCF2131.cpp.
References int_clear().
oscillator_stop()
bool PCF2131::oscillator_stop (void) virtual
Detector for oscillation stop
Returns
true, if the OSF (Oscillator Stop Flag) is set
Implements RTC_NXP.
Definition at line 29 of file PCF2131.cpp.
References intfp, and Seconds.
periodic_interrupt_enable()
void PCF2131::periodic_interrupt_enable (periodic_int_select sel, int int_sel = 0)
Enabling every second/minute interrupt
Parameters
sel choose DISABLE, EVERY_SECOND or EVERY_MINUTE in 'enum periodic_int_select'
int_sel Interrupt output selector.) for INT_A, 1 for INT_B
Definition at line 167 of file PCF2131.cpp.
References Control_1, EVERY_MINUTE, int_mask_reg, and intfp.
rtc_time()
time_t PCF2131::rtc_time (void) virtual
time
Returns
time_t value of current time
Implements RTC_NXP.
Definition at line 34 of file PCF2131.cpp.
References _100th_Seconds, RTC_NXP::bcd2dec(), and intfp.
set()
void PCF2131::set (struct tm * now_tm) virtual
set
Parameters
now_tm struct to set calendar and time in RTC
Implements RTC_NXP.
Definition at line 53 of file PCF2131.cpp.
References _100th_Seconds, Control_1, RTC_NXP::dec2bcd(), intfp, and SR_Reset.
timestamp() [1/2]
time_t PCF2131::timestamp (int num)
Getting timestamp info
Parameters
num timestamp number: 1~4
Returns
time_t
Definition at line 118 of file PCF2131.cpp.
References RTC_NXP::bcd2dec(), intfp, and Timestp_ctl1.
timestamp() [2/2]
void PCF2131::timestamp (int num, timestanp_setting ts_setting, int int_sel = 0)
Timestamp setting
Parameters
num timestamp number: 1~4
ts_setting event recording option. Choose LAST or FIRST in 'enum timestanp_setting'
int_sel Interrupt output selector.) for INT_A, 1 for INT_B
Definition at line 103 of file PCF2131.cpp.
References Control_5, int_mask_reg, intfp, and Timestp_ctl1.
Member Data Documentation
int_mask_reg
const int PCF2131::int_mask_reg[2][2] private
Initial value:
= {
        { INT_A_MASK1, INT_A_MASK2, },
        { INT_B_MASK1, INT_B_MASK2, },
    }
Definition at line 335 of file RTC_NXP.h.
intfp
std::unique_ptr<Serial_device> PCF2131::intfp private
Definition at line 339 of file RTC_NXP.h.
The documentation for this class was generated from the following files:
r01device/rtc/RTC_NXP.h
r01device/rtc/PCF2131.cpp