r01lib: TempSensor Class Reference
TempSensor Class Reference abstract
#include <TempSensor.h>
Public Types
enum mode { COMPARATOR , INTERRUPT }
using raw_t = int16_t
using celsius_t = float
Public Member Functions
TempSensor (I2C &interface, uint8_t i2c_address)
virtual ~TempSensor ()
template<class T>
T read (void)
virtual float temp (void)
operator float ()
template<>
int16_t read (void)
template<>
float read (void)
Public Member Functions inherited from I2C_device
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
virtual ~I2C_device ()
void repeated_start_enable (bool en=true)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
void write_r16 (uint8_t reg, uint16_t val)
uint8_t read_r8 (uint8_t reg)
uint16_t read_r16 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
bool ping (void)
uint8_t address (void)
void address_overwrite (uint8_t address)
virtual void ccc_set (CCC ccc, uint8_t data)
virtual uint8_t * ccc_get (CCC ccc, uint8_t *dp, uint8_t length)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Private Member Functions
virtual int16_t read_Temp_register (void)=0
Additional Inherited Members
Static Public Member Functions inherited from I2C_device
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t last=124)
Protected Attributes inherited from I2C_device
I2C & i2c
uint8_t i2c_addr
Detailed Description
TempSensor class
TempSensor class is a base class for all temperature sensors All actual device class will be inherited from this class
Definition at line 21 of file TempSensor.h.
Member Typedef Documentation
celsius_t
using TempSensor::celsius_t = float
Definition at line 25 of file TempSensor.h.
raw_t
using TempSensor::raw_t = int16_t
Definition at line 24 of file TempSensor.h.
Member Enumeration Documentation
mode
enum TempSensor::mode
Enumerator
COMPARATOR
Comparator mode
INTERRUPT
Interrupt mode
Definition at line 27 of file TempSensor.h.
Constructor & Destructor Documentation
TempSensor()
TempSensor::TempSensor (I2C & interface, uint8_t i2c_address)
Definition at line 11 of file TempSensor.cpp.
References I2C_device::I2C_device().
~TempSensor()
TempSensor::~TempSensor () virtual
Definition at line 12 of file TempSensor.cpp.
Member Function Documentation
operator float()
TempSensor::operator float ()
A short hand for reading pins
Definition at line 31 of file TempSensor.cpp.
References temp().
read() [1/3]
template<> int16_t TempSensor::read (void)
Definition at line 15 of file TempSensor.cpp.
References read_Temp_register().
read() [2/3]
template<> float TempSensor::read (void)
Definition at line 21 of file TempSensor.cpp.
References read().
read() [3/3]
template<class T> T TempSensor::read (void)
Read temperature sensor
Performs temperature sensor read.
This method need to be called with return type as celsius_t value = read<TempSensor::celsius_t>(); raw_t value = read<TempSensor::raw_t>();
Returns
temperature sensor readout value
read_Temp_register()
virtual int16_t TempSensor::read_Temp_register (void) private pure virtual
Implemented in LM75B.
temp()
float TempSensor::temp (void) virtual
Get temperature value in degree Celsius [°C]
Returns
temperature value in degree Celsius [°C]
Reimplemented in P3T1035, P3T1085, P3T1755, P3T2030, and PCT2075.
Definition at line 26 of file TempSensor.cpp.
References read().
The documentation for this class was generated from the following files:
r01device/temp_sensor/TempSensor.h
r01device/temp_sensor/TempSensor.cpp