r01lib: PCF85063_base Class Reference
PCF85063_base Class Reference abstract
#include <RTC_NXP.h>
Public Types
enum reg_num {
Control_1 , Control_2 , Offset , RAM_byte ,
Seconds , Minutes , Hours , Days ,
Weekdays , Months , Years , Second_alarm ,
Minute_alarm , Hour_alarm , Day_alarm , Weekday_alarm ,
Timer_value , Timer_mode
}
Public Types inherited from RTC_NXP
enum board { NONE , ARDUINO_SHIELD }
enum alarm_setting {
SECOND , MINUTE , HOUR , DAY ,
WEEKDAY
}
Public Member Functions
PCF85063_base ()
virtual ~PCF85063_base ()
void begin (void)
void set (struct tm *now_tm)
bool oscillator_stop (void)
void alarm (alarm_setting digit, int val)
void alarm_clear (void)
void alarm_disable (void)
uint8_t int_clear (void)
float timer (float period)
Public Member Functions inherited from RTC_NXP
RTC_NXP ()
virtual ~RTC_NXP ()
time_t time (time_t *tp)
Protected Member Functions
time_t rtc_time (void)
virtual void _reg_w (uint8_t reg, uint8_t *vp, int len)=0
virtual void _reg_r (uint8_t reg, uint8_t *vp, int len)=0
virtual void _reg_w (uint8_t reg, uint8_t val)=0
virtual uint8_t _reg_r (uint8_t reg)=0
virtual void _bit_op8 (uint8_t reg, uint8_t mask, uint8_t val)=0
Additional Inherited Members
Static Protected Member Functions inherited from RTC_NXP
static uint8_t bcd2dec (uint8_t v)
static uint8_t dec2bcd (uint8_t v)
Detailed Description
Definition at line 349 of file RTC_NXP.h.
Member Enumeration Documentation
reg_num
enum PCF85063_base::reg_num
Name of the PCF85063 registers
Enumerator
Control_1
Control_2
Offset
RAM_byte
Seconds
Minutes
Hours
Days
Weekdays
Months
Years
Second_alarm
Minute_alarm
Hour_alarm
Day_alarm
Weekday_alarm
Timer_value
Timer_mode
Definition at line 353 of file RTC_NXP.h.
Constructor & Destructor Documentation
PCF85063_base()
PCF85063_base::PCF85063_base ()
Constructor
Definition at line 9 of file PCF85063A.cpp.
~PCF85063_base()
PCF85063_base::~PCF85063_base () virtual
Destructor
Definition at line 13 of file PCF85063A.cpp.
Member Function Documentation
_bit_op8()
virtual void PCF85063_base::_bit_op8 (uint8_t reg, uint8_t mask, uint8_t val) protected pure virtual
Proxy method for interface (pure virtual method)
Implemented in PCF85063A.
_reg_r() [1/2]
virtual uint8_t PCF85063_base::_reg_r (uint8_t reg) protected pure virtual
Proxy method for interface (pure virtual method)
Implemented in PCF85063A.
_reg_r() [2/2]
virtual void PCF85063_base::_reg_r (uint8_t reg, uint8_t * vp, int len) protected pure virtual
Proxy method for interface (pure virtual method)
Implemented in PCF85063A.
_reg_w() [1/2]
virtual void PCF85063_base::_reg_w (uint8_t reg, uint8_t * vp, int len) protected pure virtual
Proxy method for interface (pure virtual method)
Implemented in PCF85063A.
_reg_w() [2/2]
virtual void PCF85063_base::_reg_w (uint8_t reg, uint8_t val) protected pure virtual
Proxy method for interface (pure virtual method)
Implemented in PCF85063A.
alarm()
void PCF85063_base::alarm (alarm_setting digit, int val) virtual
Alarm setting
Parameters
digit to specify which parameter to set: SECOND, MINUTE, HOUR, DAY, WEEKDAY in 'enum alarm_setting'
val Setting value. Set 0x80 to disabling
Implements RTC_NXP.
Reimplemented in PCF85063A.
Definition at line 49 of file PCF85063A.cpp.
References _bit_op8(), _reg_w(), Control_2, RTC_NXP::dec2bcd(), and Second_alarm.
alarm_clear()
void PCF85063_base::alarm_clear (void) virtual
Alarm clearing
Implements RTC_NXP.
Reimplemented in PCF85063A.
Definition at line 56 of file PCF85063A.cpp.
alarm_disable()
void PCF85063_base::alarm_disable (void) virtual
Alarm interrupt disable
Implements RTC_NXP.
Reimplemented in PCF85063A.
Definition at line 61 of file PCF85063A.cpp.
References _bit_op8(), and Control_2.
begin()
void PCF85063_base::begin (void) virtual
Initializer but nothing done with this menthod in this version. Don't need to call
Implements RTC_NXP.
Reimplemented in PCF85063A, and PCF85063TP.
Definition at line 17 of file PCF85063A.cpp.
int_clear()
uint8_t PCF85063_base::int_clear (void) virtual
Interrupt clear
Implements RTC_NXP.
Reimplemented in PCF85063A.
Definition at line 66 of file PCF85063A.cpp.
References _reg_r(), _reg_w(), and Control_2.
oscillator_stop()
bool PCF85063_base::oscillator_stop (void) virtual
Detector for oscillation stop
Returns
true, if the OSF (Oscillator Stop Flag) is set
Implements RTC_NXP.
Reimplemented in PCF85063A, and PCF85063TP.
Definition at line 44 of file PCF85063A.cpp.
References _reg_r(), and Seconds.
rtc_time()
time_t PCF85063_base::rtc_time (void) protected virtual
rtc_time
Returns
time_t returns RTC time in time_t format
Implements RTC_NXP.
Definition at line 106 of file PCF85063A.cpp.
References _reg_r(), RTC_NXP::bcd2dec(), and Seconds.
set()
void PCF85063_base::set (struct tm * now_tm) virtual
set
Parameters
now_tm struct to set calendar and time in RTC
Implements RTC_NXP.
Reimplemented in PCF85063A, and PCF85063TP.
Definition at line 21 of file PCF85063A.cpp.
References _bit_op8(), _reg_w(), Control_1, RTC_NXP::dec2bcd(), and Seconds.
timer()
float PCF85063_base::timer (float period)
Timer setting
Parameters
period timer interval in second
Returns
actual timer set value in second
Definition at line 74 of file PCF85063A.cpp.
References _reg_w(), Timer_mode, and Timer_value.
The documentation for this class was generated from the following files:
r01device/rtc/RTC_NXP.h
r01device/rtc/PCF85063A.cpp