r01lib: I2C_Character_LCD Class Reference
I2C_Character_LCD Class Reference
#include <I2C_Character_LCD.h>
Public Member Functions
I2C_Character_LCD (I2C &i2c, uint8_t address, const std::vector< uint8_t > &line_select, size_t width=16, uint8_t command_byte=0x00, uint8_t data_byte=0x40)
virtual ~I2C_Character_LCD ()=default
void send (bool data_flag, uint8_t value)
void command (uint8_t command)
void data (uint8_t data)
void clear (void)
void putc (char c)
void puts (const char *str, size_t line_num=0)
void printf (uint8_t line_num, const char *format,...)
Public Member Functions inherited from I2C_device
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
virtual ~I2C_device ()
void repeated_start_enable (bool en=true)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
void write_r16 (uint8_t reg, uint16_t val)
uint8_t read_r8 (uint8_t reg)
uint16_t read_r16 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
bool ping (void)
uint8_t address (void)
void address_overwrite (uint8_t address)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Protected Attributes
size_t lines
uint8_t command_byte
uint8_t data_byte
size_t width
std::vector< uint8_t > line_select
Protected Attributes inherited from I2C_device
I2C & i2c
uint8_t i2c_addr
Additional Inherited Members
Static Public Member Functions inherited from I2C_device
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t last=124)
Detailed Description
Definition at line 18 of file I2C_Character_LCD.h.
Constructor & Destructor Documentation
I2C_Character_LCD()
I2C_Character_LCD::I2C_Character_LCD (I2C & i2c, uint8_t address, const std::vector< uint8_t > & line_select, size_t width = 16, uint8_t command_byte = 0x00, uint8_t data_byte = 0x40)
Definition at line 11 of file I2C_Character_LCD.cpp.
References command_byte, data_byte, I2C_device::I2C_device(), line_select, lines, and width.
~I2C_Character_LCD()
virtual I2C_Character_LCD::~I2C_Character_LCD () virtual default
References command(), and data().
Member Function Documentation
clear()
void I2C_Character_LCD::clear (void)
Definition at line 34 of file I2C_Character_LCD.cpp.
References command().
command()
void I2C_Character_LCD::command (uint8_t command)
Definition at line 21 of file I2C_Character_LCD.cpp.
References command(), send(), wait_ms(), and wait_us().
data()
void I2C_Character_LCD::data (uint8_t data)
Definition at line 28 of file I2C_Character_LCD.cpp.
References send(), and wait_ms().
printf()
void I2C_Character_LCD::printf (uint8_t line_num, const char * format, ...)
Definition at line 59 of file I2C_Character_LCD.cpp.
References MAX_PRINTF_LENGTH, and puts().
putc()
void I2C_Character_LCD::putc (char c)
Definition at line 39 of file I2C_Character_LCD.cpp.
References data().
puts()
void I2C_Character_LCD::puts (const char * str, size_t line_num = 0)
Definition at line 44 of file I2C_Character_LCD.cpp.
References command(), line_select, lines, and putc().
send()
void I2C_Character_LCD::send (bool data_flag, uint8_t value)
Definition at line 16 of file I2C_Character_LCD.cpp.
References command_byte, data_byte, and I2C_device::reg_w().
Member Data Documentation
command_byte
uint8_t I2C_Character_LCD::command_byte protected
Definition at line 35 of file I2C_Character_LCD.h.
data_byte
uint8_t I2C_Character_LCD::data_byte protected
Definition at line 36 of file I2C_Character_LCD.h.
line_select
std::vector<uint8_t> I2C_Character_LCD::line_select protected
Definition at line 38 of file I2C_Character_LCD.h.
lines
size_t I2C_Character_LCD::lines protected
Definition at line 34 of file I2C_Character_LCD.h.
width
size_t I2C_Character_LCD::width protected
Definition at line 37 of file I2C_Character_LCD.h.
The documentation for this class was generated from the following files:
r01device/misc/lcd/I2C_Character_LCD.h
r01device/misc/lcd/I2C_Character_LCD.cpp