r01lib: PCA8561 Class Reference
PCA8561 Class Reference
#include <LCDDriver.h>
Public Types
enum reg_num {
Software_reset , Device_ctrl , Display_ctrl_1 , Display_ctrl_2 ,
COM0_07_00 , COM0_15_08 , COM0_17_16 , COM1_07_00 ,
COM1_15_08 , COM1_17_16 , COM2_07_00 , COM2_15_08 ,
COM2_17_16 , COM3_07_00 , COM3_15_08 , COM3_17_16
}
Public Member Functions
PCA8561 (I2C &interface, uint8_t i2c_address=(0x70 > > 1))
virtual ~PCA8561 ()
void begin (void)
void com_seg (int com, int seg, bool v)
void puts (const char *s, int dly=0)
void putchar (char c)
void clear (bool no_flush=false)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
uint8_t read_r8 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
Public Member Functions inherited from I2C_device
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
virtual ~I2C_device ()
void repeated_start_enable (bool en=true)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
void write_r16 (uint8_t reg, uint16_t val)
uint16_t read_r16 (uint8_t reg)
bool ping (void)
uint8_t address (void)
void address_overwrite (uint8_t address)
virtual void ccc_set (CCC ccc, uint8_t data)
virtual uint8_t * ccc_get (CCC ccc, uint8_t *dp, uint8_t length)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Static Public Attributes
static constexpr int N_COM = 4
static constexpr int N_SEG = 18
Private Member Functions
void init (void)
void flush (void)
void char2seg (int pos, int c)
Private Attributes
uint8_t bf [12]
char str_buffer [4]
int str_pos = 0
Static Private Attributes
static uint16_t char_pattern [61]
Additional Inherited Members
Static Public Member Functions inherited from I2C_device
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t last=124)
Protected Attributes inherited from I2C_device
I2C & i2c
uint8_t i2c_addr
Detailed Description
PCA8561 class
PCA8561 class is a sample code for the PCA8561AHN-ARD It demonstrates LCD operation by
Definition at line 21 of file LCDDriver.h.
Member Enumeration Documentation
reg_num
enum PCA8561::reg_num
Enumerator
Software_reset
Device_ctrl
Display_ctrl_1
Display_ctrl_2
COM0_07_00
COM0_15_08
COM0_17_16
COM1_07_00
COM1_15_08
COM1_17_16
COM2_07_00
COM2_15_08
COM2_17_16
COM3_07_00
COM3_15_08
COM3_17_16
Definition at line 29 of file LCDDriver.h.
Constructor & Destructor Documentation
PCA8561()
PCA8561::PCA8561 (I2C & interface, uint8_t i2c_address = (0x70 >> 1))
Create a PCA8561 instance with specified address
Parameters
interface I2C instance
i2c_address I2C-bus address (default: (0x70>>1))
Definition at line 13 of file LCDDriver.cpp.
References I2C_device::I2C_device(), and init().
~PCA8561()
PCA8561::~PCA8561 () virtual
Definition at line 28 of file LCDDriver.cpp.
Member Function Documentation
begin()
void PCA8561::begin (void)
Begin the device operation
This method turns-on the device
Definition at line 32 of file LCDDriver.cpp.
References Display_ctrl_1, and reg_w().
bit_op16()
void PCA8561::bit_op16 (uint8_t reg, uint16_t mask, uint16_t value) virtual
Reimplemented from I2C_device.
bit_op8()
void PCA8561::bit_op8 (uint8_t reg, uint8_t mask, uint8_t value) virtual
Register overwriting with bit-mask
Register can be updated by bit level
Parameters
reg register index/address/pointer
mask bit-mask to protect overwriting
value value to overwrite
Reimplemented from I2C_device.
char2seg()
void PCA8561::char2seg (int pos, int c) private
Definition at line 96 of file LCDDriver.cpp.
References bf, and char_pattern.
clear()
void PCA8561::clear (bool no_flush = false)
Clear display
Parameters
no_flush no immidiate display clear (display will be cleared at next "putchar()" or "puts()" call)
Definition at line 85 of file LCDDriver.cpp.
References bf, flush(), and str_pos.
com_seg()
void PCA8561::com_seg (int com, int seg, bool v)
Access to a segment
Parameters
com LCD backplane output select
seg LCD segment output select
v true for the segment ON
Definition at line 37 of file LCDDriver.cpp.
References bit_op8(), COM0_07_00, COM0_15_08, COM0_17_16, COM1_07_00, COM1_15_08, COM1_17_16, COM2_07_00, COM2_15_08, COM2_17_16, COM3_07_00, COM3_15_08, and COM3_17_16.
flush()
void PCA8561::flush (void) private
Definition at line 80 of file LCDDriver.cpp.
References bf, COM0_07_00, and reg_w().
init()
void PCA8561::init (void) private
Definition at line 18 of file LCDDriver.cpp.
References bf, Display_ctrl_1, reg_w(), and str_pos.
putchar()
void PCA8561::putchar (char c)
Character output
Putting '
' or '\r' character to clear display in next "putchar()" or "puts()" call
Parameters
c A character to display
Definition at line 57 of file LCDDriver.cpp.
References char2seg(), clear(), flush(), str_buffer, and str_pos.
puts()
void PCA8561::puts (const char * s, int dly = 0)
String output
Parameters
s A string to display
dly Option parameter for scroll effect each character appears with this delay [mili-second] (default: 0)
Definition at line 49 of file LCDDriver.cpp.
References putchar(), and wait().
read_r8()
uint8_t PCA8561::read_r8 (uint8_t reg) virtual
Register read, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
Reimplemented from I2C_device.
reg_r() [1/2]
uint8_t PCA8561::reg_r (uint8_t reg_adr) virtual
Single register read
Parameters
reg register index/address/pointer
Returns
read data
Reimplemented from I2C_device.
reg_r() [2/2]
int PCA8561::reg_r (uint8_t reg_adr, uint8_t * data, uint16_t size) virtual
Multiple register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Reimplemented from I2C_device.
reg_w() [1/2]
int PCA8561::reg_w (uint8_t reg_adr, const uint8_t * data, uint16_t size) virtual
Multiple register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Reimplemented from I2C_device.
reg_w() [2/2]
int PCA8561::reg_w (uint8_t reg_adr, uint8_t data) virtual
Single register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Reimplemented from I2C_device.
write_r8()
void PCA8561::write_r8 (uint8_t reg, uint8_t val) virtual
Register write, 8 bit
Parameters
reg register index/address/pointer
val data value
Reimplemented from I2C_device.
Member Data Documentation
bf
uint8_t PCA8561::bf[12] private
Definition at line 148 of file LCDDriver.h.
char_pattern
uint16_t PCA8561::char_pattern static private
Initial value:
= {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x4001,
    0x0000, 0x0000, 0x2AA8, 0x8282, 0x8282, 0x0280, 0x4000, 0x0820,
    0x1D74, 0x0440, 0x13C4, 0x16C4, 0x06D0, 0x1694, 0x1794, 0x0444,
    0x17D4, 0x16D4, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x07D4, 0x17B4, 0x1114, 0x9446, 0x1394, 0x0394, 0x1714,
    0x07D0, 0x9006, 0x1540, 0x21B0, 0x1110, 0x0578, 0x2558, 0x1554,
    0x03D4, 0x3554, 0x23D4, 0x1694, 0x8006, 0x1550, 0x0930, 0x2D50,
    0x2828, 0x8028, 0x1824, 0x0000, 0x2008,
}
Definition at line 121 of file LCDDriver.h.
N_COM
int PCA8561::N_COM = 4 static constexpr
The number of LCD backplane output
Definition at line 25 of file LCDDriver.h.
N_SEG
int PCA8561::N_SEG = 18 static constexpr
The number of LCD segment output
Definition at line 28 of file LCDDriver.h.
str_buffer
char PCA8561::str_buffer[4] private
Definition at line 149 of file LCDDriver.h.
str_pos
int PCA8561::str_pos = 0 private
Definition at line 150 of file LCDDriver.h.
The documentation for this class was generated from the following files:
r01device/lcd/LCDDriver.h
r01device/lcd/LCDDriver.cpp