r01lib: PCA995x_I2C Class Reference
PCA995x_I2C Class Reference
#include <LEDDriver.h>
Public Member Functions
PCA995x_I2C (I2C &interface, uint8_t i2c_address, uint8_t n_ch, uint8_t PWM_r, uint8_t IREF_r, uint8_t IREFALL_r, const uint8_t *ar, uint8_t oe=D8)
virtual ~PCA995x_I2C ()
void reg_access (uint8_t reg, uint8_t val)
void reg_access (uint8_t reg, uint8_t *vp, int len)
uint8_t reg_access (uint8_t reg)
void reg_access_r (uint8_t reg, uint8_t *vp, int len)
Public Member Functions inherited from PCA995x
PCA995x (uint8_t n_ch, uint8_t PWM_r, uint8_t IREF_r, uint8_t IREFALL_r, const uint8_t *ar, uint8_t oe=D8)
virtual ~PCA995x ()
virtual void begin (float current=0.1, board env=NONE, bool buffered=false)
virtual void init (float current)=0
void irefall (uint8_t iref)
Public Member Functions inherited from LEDDriver
LEDDriver (uint8_t n_ch, uint8_t PWM_r, uint8_t oe)
virtual ~LEDDriver ()
void pwm (uint8_t ch, float value)
void pwm (float *values)
void buffer_enable (bool flag)
void flush (void)
Public Member Functions inherited from I2C_device
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
virtual ~I2C_device ()
void repeated_start_enable (bool en=true)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
void write_r16 (uint8_t reg, uint16_t val)
uint8_t read_r8 (uint8_t reg)
uint16_t read_r16 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
bool ping (void)
uint8_t address (void)
void address_overwrite (uint8_t address)
virtual void ccc_set (CCC ccc, uint8_t data)
virtual uint8_t * ccc_get (CCC ccc, uint8_t *dp, uint8_t length)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Additional Inherited Members
Public Types inherited from LEDDriver
enum board { NONE , ARDUINO_SHIELD }
Static Public Member Functions inherited from I2C_device
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t last=124)
Public Attributes inherited from PCA995x
const uint8_t * arp
Public Attributes inherited from LEDDriver
const uint8_t n_channel
Protected Attributes inherited from PCA995x
const uint8_t reg_IREF
const uint8_t reg_IREFALL
Protected Attributes inherited from LEDDriver
const uint8_t reg_PWM
const uint8_t oe_pin
Protected Attributes inherited from I2C_device
I2C & i2c
uint8_t i2c_addr
Detailed Description
Definition at line 122 of file LEDDriver.h.
Constructor & Destructor Documentation
PCA995x_I2C()
PCA995x_I2C::PCA995x_I2C (I2C & interface, uint8_t i2c_address, uint8_t n_ch, uint8_t PWM_r, uint8_t IREF_r, uint8_t IREFALL_r, const uint8_t * ar, uint8_t oe = D8)
Definition at line 102 of file LEDDriver.cpp.
References I2C_device::I2C_device(), and PCA995x::PCA995x().
~PCA995x_I2C()
PCA995x_I2C::~PCA995x_I2C () virtual
Definition at line 108 of file LEDDriver.cpp.
Member Function Documentation
reg_access() [1/3]
uint8_t PCA995x_I2C::reg_access (uint8_t reg) virtual
Implements LEDDriver.
Definition at line 122 of file LEDDriver.cpp.
References I2C_device::read_r8().
reg_access() [2/3]
void PCA995x_I2C::reg_access (uint8_t reg, uint8_t * vp, int len) virtual
Implements LEDDriver.
Definition at line 117 of file LEDDriver.cpp.
References I2C_device::reg_w().
reg_access() [3/3]
void PCA995x_I2C::reg_access (uint8_t reg, uint8_t val) virtual
Implements LEDDriver.
Definition at line 112 of file LEDDriver.cpp.
References I2C_device::write_r8().
reg_access_r()
void PCA995x_I2C::reg_access_r (uint8_t reg, uint8_t * vp, int len) virtual
Implements LEDDriver.
Definition at line 127 of file LEDDriver.cpp.
References I2C_device::reg_r().
The documentation for this class was generated from the following files:
r01device/led/LEDDriver.h
r01device/led/LEDDriver.cpp