r01lib: NAFE13388_Base::LogicalChannel Class Reference
NAFE13388_Base::LogicalChannel Class Reference
#include <AFE_NXP.h>
Public Member Functions
LogicalChannel (AFE_base &a, uint8_t ch, const uint16_t(&cc)[4])
LogicalChannel (AFE_base &a, uint8_t ch, uint16_t cc0=0x0000, uint16_t cc1=0x0000, uint16_t cc2=0x0000, uint16_t cc3=0x0000)
virtual ~LogicalChannel ()
void update (const uint16_t(&cc)[4])
void update (uint16_t cc0=0x0000, uint16_t cc1=0x0000, uint16_t cc2=0x0000, uint16_t cc3=0x0000)
void enable (void)
void disable (void)
template<class T>
T read (void)
template<class T>
operator T (void)
template<>
NAFE13388_Base::raw_t read (void)
Public Attributes
AFE_base & afe
uint8_t ch_number
Detailed Description
Definition at line 386 of file AFE_NXP.h.
Constructor & Destructor Documentation
LogicalChannel() [1/2]
NAFE13388_Base::LogicalChannel::LogicalChannel (AFE_base & a, uint8_t ch, const uint16_t(&) cc[4])
Definition at line 21 of file AFE_NXP.cpp.
References afe, AFE_base::AFE_base(), ch_number, and update().
LogicalChannel() [2/2]
NAFE13388_Base::LogicalChannel::LogicalChannel (AFE_base & a, uint8_t ch, uint16_t cc0 = 0x0000, uint16_t cc1 = 0x0000, uint16_t cc2 = 0x0000, uint16_t cc3 = 0x0000)
Definition at line 26 of file AFE_NXP.cpp.
References afe, AFE_base::AFE_base(), ch_number, and update().
~LogicalChannel()
NAFE13388_Base::LogicalChannel::~LogicalChannel () virtual
Definition at line 31 of file AFE_NXP.cpp.
References disable().
Member Function Documentation
disable()
void NAFE13388_Base::LogicalChannel::disable (void)
Definition at line 52 of file AFE_NXP.cpp.
References afe, and ch_number.
enable()
void NAFE13388_Base::LogicalChannel::enable (void)
Definition at line 47 of file AFE_NXP.cpp.
References afe, and ch_number.
operator T()
template<class T> NAFE13388_Base::LogicalChannel::operator T (void)
read() [1/2]
NAFE13388_Base::microvolt_t NAFE13388_Base::LogicalChannel::read (void)
Definition at line 58 of file AFE_NXP.cpp.
References afe, and ch_number.
read() [2/2]
template<class T> T NAFE13388_Base::LogicalChannel::read (void)
update() [1/2]
void NAFE13388_Base::LogicalChannel::update (const uint16_t(&) cc[4])
Definition at line 36 of file AFE_NXP.cpp.
References afe, and ch_number.
update() [2/2]
void NAFE13388_Base::LogicalChannel::update (uint16_t cc0 = 0x0000, uint16_t cc1 = 0x0000, uint16_t cc2 = 0x0000, uint16_t cc3 = 0x0000)
Definition at line 41 of file AFE_NXP.cpp.
References afe, and ch_number.
Member Data Documentation
afe
AFE_base& NAFE13388_Base::LogicalChannel::afe
Definition at line 389 of file AFE_NXP.h.
ch_number
uint8_t NAFE13388_Base::LogicalChannel::ch_number
Definition at line 390 of file AFE_NXP.h.
The documentation for this class was generated from the following files:
r01device/afe/AFE_NXP.h
r01device/afe/AFE_NXP.cpp