r01lib: PCA995x Class Reference
PCA995x Class Reference abstract
#include <LEDDriver.h>
Public Member Functions
PCA995x (uint8_t n_ch, uint8_t PWM_r, uint8_t IREF_r, uint8_t IREFALL_r, const uint8_t *ar, uint8_t oe=D8)
virtual ~PCA995x ()
virtual void begin (float current=0.1, board env=NONE, bool buffered=false)
virtual void init (float current)=0
void irefall (uint8_t iref)
Public Member Functions inherited from LEDDriver
LEDDriver (uint8_t n_ch, uint8_t PWM_r, uint8_t oe)
virtual ~LEDDriver ()
virtual void reg_access (uint8_t reg, uint8_t val)=0
virtual void reg_access (uint8_t reg, uint8_t *vp, int len)=0
virtual uint8_t reg_access (uint8_t reg)=0
virtual void reg_access_r (uint8_t reg, uint8_t *vp, int len)=0
void pwm (uint8_t ch, float value)
void pwm (float *values)
void buffer_enable (bool flag)
void flush (void)
Public Attributes
const uint8_t * arp
Public Attributes inherited from LEDDriver
const uint8_t n_channel
Protected Attributes
const uint8_t reg_IREF
const uint8_t reg_IREFALL
Protected Attributes inherited from LEDDriver
const uint8_t reg_PWM
const uint8_t oe_pin
Additional Inherited Members
Public Types inherited from LEDDriver
enum board { NONE , ARDUINO_SHIELD }
Detailed Description
PCA995x class
Base class to abstract behavior of PCA995x series
Definition at line 98 of file LEDDriver.h.
Constructor & Destructor Documentation
PCA995x()
PCA995x::PCA995x (uint8_t n_ch, uint8_t PWM_r, uint8_t IREF_r, uint8_t IREFALL_r, const uint8_t * ar, uint8_t oe = D8)
Definition at line 71 of file LEDDriver.cpp.
References arp, LEDDriver::LEDDriver(), reg_IREF, and reg_IREFALL.
~PCA995x()
PCA995x::~PCA995x () virtual
Definition at line 78 of file LEDDriver.cpp.
Member Function Documentation
begin()
void PCA995x::begin (float current = 0.1, board env = NONE, bool buffered = false) virtual
Definition at line 82 of file LEDDriver.cpp.
References LEDDriver::buffer_enable(), init(), and LEDDriver::oe_pin.
init()
virtual void PCA995x::init (float current) pure virtual
Implemented in PCA9955B, PCA9956B, and PCA9957.
irefall()
void PCA995x::irefall (uint8_t iref)
Set IREFALL value (current setting for all channels)
Parameters
value current value in float (0.0 ~ 1.0)
Definition at line 93 of file LEDDriver.cpp.
References LEDDriver::reg_access(), and reg_IREFALL.
Member Data Documentation
arp
const uint8_t* PCA995x::arp
Definition at line 118 of file LEDDriver.h.
reg_IREF
const uint8_t PCA995x::reg_IREF protected
Definition at line 114 of file LEDDriver.h.
reg_IREFALL
const uint8_t PCA995x::reg_IREFALL protected
Definition at line 115 of file LEDDriver.h.
The documentation for this class was generated from the following files:
r01device/led/LEDDriver.h
r01device/led/LEDDriver.cpp