r01lib: SPI_for_RTC Class Reference
SPI_for_RTC Class Reference
#include <RTC_NXP.h>
Public Member Functions
SPI_for_RTC (SPI &interface)
~SPI_for_RTC ()
void txrx (uint8_t *data, int size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
uint8_t read_r8 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
virtual void write_r16 (uint8_t reg, uint16_t val)
virtual uint16_t read_r16 (uint8_t reg)
virtual void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
Private Attributes
SPI & spi
Detailed Description
SPI_for_RTC class
SPI interface operation for RTC devices
Definition at line 121 of file RTC_NXP.h.
Constructor & Destructor Documentation
SPI_for_RTC()
SPI_for_RTC::SPI_for_RTC (SPI & interface)
Definition at line 9 of file SPI_for_RTC.cpp.
References spi.
~SPI_for_RTC()
SPI_for_RTC::~SPI_for_RTC ()
Definition at line 10 of file SPI_for_RTC.cpp.
Member Function Documentation
bit_op8()
void SPI_for_RTC::bit_op8 (uint8_t reg, uint8_t mask, uint8_t value) virtual
Register overwriting with bit-mask
Register can be updated by bit level
Parameters
reg register index/address/pointer
mask bit-mask to protect overwriting
value value to overwrite
Implements Serial_device.
Definition at line 75 of file SPI_for_RTC.cpp.
References reg_r(), and reg_w().
read_r8()
uint8_t SPI_for_RTC::read_r8 (uint8_t reg) virtual
Register read, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
Implements Serial_device.
Definition at line 70 of file SPI_for_RTC.cpp.
References reg_r().
reg_r() [1/2]
uint8_t SPI_for_RTC::reg_r (uint8_t reg_adr) virtual
Single register read
Parameters
reg register index/address/pointer
Returns
read data
Implements Serial_device.
Definition at line 56 of file SPI_for_RTC.cpp.
References txrx().
reg_r() [2/2]
int SPI_for_RTC::reg_r (uint8_t reg_adr, uint8_t * data, uint16_t size) virtual
Multiple register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Implements Serial_device.
Definition at line 41 of file SPI_for_RTC.cpp.
References txrx().
reg_w() [1/2]
int SPI_for_RTC::reg_w (uint8_t reg_adr, const uint8_t * data, uint16_t size) virtual
Multiple register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Implements Serial_device.
Definition at line 20 of file SPI_for_RTC.cpp.
References txrx().
reg_w() [2/2]
int SPI_for_RTC::reg_w (uint8_t reg_adr, uint8_t data) virtual
Single register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Implements Serial_device.
Definition at line 32 of file SPI_for_RTC.cpp.
References txrx().
txrx()
void SPI_for_RTC::txrx (uint8_t * data, int size)
Send data
Parameters
data pointer to data buffer
size data size
stop option: generating STOP-condition after transaction. Defailt: true
Returns
transferred data size
Definition at line 12 of file SPI_for_RTC.cpp.
References spi.
write_r8()
void SPI_for_RTC::write_r8 (uint8_t reg, uint8_t val) virtual
Register write, 8 bit
Parameters
reg register index/address/pointer
val data value
Implements Serial_device.
Definition at line 65 of file SPI_for_RTC.cpp.
References reg_w().
Member Data Documentation
spi
SPI& SPI_for_RTC::spi private
Definition at line 195 of file RTC_NXP.h.
The documentation for this class was generated from the following files:
r01device/rtc/RTC_NXP.h
r01device/rtc/SPI_for_RTC.cpp