r01lib: SPI Class Reference
SPI Class Reference
#include <spi.h>
Public Member Functions
SPI (int mosi=D11, int miso=D12, int sclk=D13, int cs=D10)
virtual ~SPI ()
virtual void frequency (uint32_t frequency=SPI_FREQ)
virtual void mode (uint8_t mode=0)
virtual status_t write (uint8_t *wp, uint8_t *rp, int length)
Public Member Functions inherited from Obj
Obj (bool done=false)
virtual ~Obj ()
Public Attributes
status_t last_status
Private Attributes
lpspi_master_config_t masterConfig
LPSPI_Type * unit_base
uint32_t master_clk_freq
uint32_t master_pcs_4_xfer
Detailed Description
SPI class
A class for demonstrating SPI bus
Definition at line 26 of file spi.h.
Constructor & Destructor Documentation
SPI()
SPI::SPI (int mosi = D11, int miso = D12, int sclk = D13, int cs = D10)
Create a SPI instance with specified pins
Parameters
mosi (option) pin number to connect MOSI
miso (option) pin number to connect MISO
sclk (option) pin number to connect SCLK
cs (option) pin number to connect CS
Definition at line 61 of file spi.cpp.
References frequency(), master_clk_freq, master_pcs_4_xfer, masterConfig, mode(), Obj::Obj(), panic(), DigitalInOut::pin_mux(), SPI_FREQ, and unit_base.
~SPI()
SPI::~SPI () virtual
Destractor to freeing SPI resource
Definition at line 130 of file spi.cpp.
References unit_base.
Member Function Documentation
frequency()
void SPI::frequency (uint32_t frequency = SPI_FREQ) virtual
Frequency settings
Parameters
frequency (option) define default SCLK frequency
Definition at line 135 of file spi.cpp.
References frequency(), master_clk_freq, masterConfig, and unit_base.
mode()
void SPI::mode (uint8_t mode = 0) virtual
mode setting SPI bus mode setting mode 0 = CPOL:0, CPHA:0 mode 1 = CPOL:0, CPHA:1 mode 2 = CPOL:1, CPHA:0 mode 3 = CPOL:1, CPHA:1
Parameters
mode selecting mode 0~3
Definition at line 147 of file spi.cpp.
References master_clk_freq, masterConfig, mode(), and unit_base.
write()
status_t SPI::write (uint8_t * wp, uint8_t * rp, int length) virtual
Data transfer on SPI
Parameters
wp data to write
rp data buffer for read
length transfer length
Definition at line 156 of file spi.cpp.
References master_pcs_4_xfer, and unit_base.
Member Data Documentation
last_status
status_t SPI::last_status
variable for reporting last state
Definition at line 69 of file spi.h.
master_clk_freq
uint32_t SPI::master_clk_freq private
Definition at line 74 of file spi.h.
master_pcs_4_xfer
uint32_t SPI::master_pcs_4_xfer private
Definition at line 75 of file spi.h.
masterConfig
lpspi_master_config_t SPI::masterConfig private
Definition at line 72 of file spi.h.
unit_base
LPSPI_Type* SPI::unit_base private
Definition at line 73 of file spi.h.
The documentation for this class was generated from the following files:
r01lib/spi.h
r01lib/spi.cpp