r01lib: GPIO_base Class Reference
GPIO_base Class Reference
#include <GPIO_NXP.h>
Public Types
enum board { NONE , ARDUINO_SHIELD }
Public Member Functions
GPIO_base (I2C &interface, uint8_t i2c_address, int nbits, const uint8_t *arp, uint8_t ai)
GPIO_base (SPI &interface, uint8_t dev_address, int nbits, const uint8_t *arp, uint8_t ai)
virtual ~GPIO_base ()
virtual void begin (board env=NONE)
void output (int port, uint8_t value, uint8_t mask=0)
void output (const uint8_t *vp)
uint8_t input (int port)
uint8_t * input (uint8_t *vp)
void config (int port, uint8_t config, uint8_t mask=0)
void config (const uint8_t *vp)
void write_port (access_word w, const uint8_t *vp)
void write_port16 (access_word w, const uint16_t *vp)
uint8_t * read_port (access_word w, uint8_t *vp)
uint16_t * read_port16 (access_word w, uint16_t *vp)
void write_port (access_word w, uint8_t value, int port_num=0)
void write_port16 (access_word w, uint16_t value, int port_num=0)
uint8_t read_port (access_word w, int port_num=0)
uint16_t read_port16 (access_word w, int port_num=0)
void init (void)
Static Public Member Functions
static void print_bin (uint8_t v)
Public Attributes
const int n_bits
const int n_ports
Private Attributes
const uint8_t * arp
const uint8_t auto_increment
bool endian
std::unique_ptr< Serial_device > intfp
Static Private Attributes
static constexpr int RESET_PIN = D8
static constexpr int ADDR_PIN = D9
Detailed Description
GPIO_base class
This class is a base class for all GPIO devices All actual device class will be derived from this
Definition at line 45 of file GPIO_NXP.h.
Member Enumeration Documentation
board
enum GPIO_base::board
Enumerator
NONE
ARDUINO_SHIELD
Definition at line 48 of file GPIO_NXP.h.
Constructor & Destructor Documentation
GPIO_base() [1/2]
GPIO_base::GPIO_base (I2C & interface, uint8_t i2c_address, int nbits, const uint8_t * arp, uint8_t ai)
Constractor
Parameters
interface I2C instance
i2c_address I2C target address
nbits Number of IO bits
arp Pointer to register access reference table
ai Auto-increment flag
Definition at line 11 of file GPIO_NXP.cpp.
References arp, auto_increment, init(), intfp, n_bits, and n_ports.
GPIO_base() [2/2]
GPIO_base::GPIO_base (SPI & interface, uint8_t dev_address, int nbits, const uint8_t * arp, uint8_t ai)
Constractor
Parameters
interface I2C instance
i2c_address I2C target address
nbits Number of IO bits
arp Pointer to register access reference table
ai Auto-increment flag
Definition at line 21 of file GPIO_NXP.cpp.
References arp, auto_increment, init(), intfp, n_bits, and n_ports.
~GPIO_base()
GPIO_base::~GPIO_base () virtual
Destractor
Definition at line 39 of file GPIO_NXP.cpp.
Member Function Documentation
begin()
void GPIO_base::begin (board env = NONE) virtual
Device/board initialization
This method is needed to initialize Arduino-shield type evaluation boards from NXP. This method takes one argument of "GPIO_base::ARDUINO_SHIELD" to set RESET and ADDRESS pins.
If the devoce is used as it self, this method doesn't need to be called.
Parameters
env This argument can be given as "GPIO_base::NONE" ot "GPIO_base::ARDUINO_SHIELD"
Reimplemented in PCAL9722.
Definition at line 43 of file GPIO_NXP.cpp.
References ADDR_PIN, RESET_PIN, and wait().
config() [1/2]
void GPIO_base::config (const uint8_t * vp)
Config, all ports
Basic GPIO port access function for all port configuration
Parameters
vp Pointer to array of configuration values. The array should have 'n_ports' length
Definition at line 93 of file GPIO_NXP.cpp.
References CONFIG, and write_port().
config() [2/2]
void GPIO_base::config (int port, uint8_t config, uint8_t mask = 0)
Config, single port
Basic GPIO port access function for single port configuration
Parameters
port Port number
value Value to be written into configuration register
mask Bit mask. Value will not be changed in bit positions '1' in mask
Definition at line 85 of file GPIO_NXP.cpp.
References arp, CONFIG, config(), and intfp.
init()
void GPIO_base::init (void)
Definition at line 31 of file GPIO_NXP.cpp.
References endian.
input() [1/2]
uint8_t GPIO_base::input (int port)
Input, single port
Basic GPIO port access function for single port input
Parameters
port Port number
Returns
Port read value
Definition at line 73 of file GPIO_NXP.cpp.
References arp, IN, and intfp.
input() [2/2]
uint8_t * GPIO_base::input (uint8_t * vp)
Input, all ports
Basic GPIO port access function for all ports input
Parameters
vp Pointer to an array of values. The array should have 'n_ports' length
Returns
Pointer to vp
Definition at line 78 of file GPIO_NXP.cpp.
References IN, and read_port().
output() [1/2]
void GPIO_base::output (const uint8_t * vp)
Output, all ports
Basic GPIO port access function for all ports output
Parameters
vp Pointer to an array of values. The array should have 'n_ports' length
Definition at line 68 of file GPIO_NXP.cpp.
References OUT, and write_port().
output() [2/2]
void GPIO_base::output (int port, uint8_t value, uint8_t mask = 0)
Output, single port
Basic GPIO port access function for single port output
Parameters
port Port number
value Value to be output
mask Bit mask. Value will not be changed in bit positions '1' in mask
Definition at line 60 of file GPIO_NXP.cpp.
References arp, intfp, and OUT.
print_bin()
void GPIO_base::print_bin (uint8_t v) static
Definition at line 193 of file GPIO_NXP.cpp.
read_port() [1/2]
uint8_t GPIO_base::read_port (access_word w, int port_num = 0)
Read single port method
Single port register access function using word of 'access_word'
Parameters
w Accsess word. This should be choosen from access_word'
port_num Option, to specify port number
Returns
Register read value
Definition at line 183 of file GPIO_NXP.cpp.
References arp, and intfp.
read_port() [2/2]
uint8_t * GPIO_base::read_port (access_word w, uint8_t * vp)
Read all port method
All port register access function using word of 'access_word'
Parameters
w Accsess word. This should be choosen from access_word'
vp Pointer to an array of values. The array should have 'n_ports' length
Returns
Pointer to vp
Definition at line 135 of file GPIO_NXP.cpp.
References arp, auto_increment, intfp, and n_ports.
read_port16() [1/2]
uint16_t GPIO_base::read_port16 (access_word w, int port_num = 0)
Read single port method
Single port 16 bit register access function using word of 'access_word'
Parameters
w Accsess word. This should be choosen from access_word'
port_num Option, to specify port number
Returns
Register read value
Definition at line 188 of file GPIO_NXP.cpp.
References arp, and intfp.
read_port16() [2/2]
uint16_t * GPIO_base::read_port16 (access_word w, uint16_t * vp)
Read all port method
All port 16 bit register access function using word of 'access_word'
Parameters
w Accsess word. This should be choosen from access_word'
vp Pointer to an array of values. The array should have 'n_ports' length
Returns
Pointer to vp
Definition at line 148 of file GPIO_NXP.cpp.
References arp, auto_increment, endian, intfp, n_bits, and n_ports.
write_port() [1/2]
void GPIO_base::write_port (access_word w, const uint8_t * vp)
Write all port method
All port register access function using word of 'access_word'
Parameters
w Accsess word. This should be choosen from access_word'
vp Pointer to an array of values. The array should have 'n_ports' length
Definition at line 98 of file GPIO_NXP.cpp.
References arp, auto_increment, intfp, and n_ports.
write_port() [2/2]
void GPIO_base::write_port (access_word w, uint8_t value, int port_num = 0)
Write single port method
Single port register access function using word of 'access_word'
Parameters
w Accsess word. This should be choosen from access_word'
value Value to be written into a register
port_num Option, to specify port number
Definition at line 173 of file GPIO_NXP.cpp.
References arp, and intfp.
write_port16() [1/2]
void GPIO_base::write_port16 (access_word w, const uint16_t * vp)
Write all port method
All port 16 bit register access function using word of 'access_word'
Parameters
w Accsess word. This should be choosen from access_word'
vp Pointer to an array of values. The array should have 'n_ports' length
Definition at line 109 of file GPIO_NXP.cpp.
References arp, auto_increment, endian, intfp, n_bits, and n_ports.
write_port16() [2/2]
void GPIO_base::write_port16 (access_word w, uint16_t value, int port_num = 0)
Write single port method
Single port 16 bit register access function using word of 'access_word'
Parameters
w Accsess word. This should be choosen from access_word'
value Value to be written into a register
port_num Option, to specify port number
Definition at line 178 of file GPIO_NXP.cpp.
References arp, and intfp.
Member Data Documentation
ADDR_PIN
int GPIO_base::ADDR_PIN = D9 static constexpr private
Definition at line 236 of file GPIO_NXP.h.
arp
const uint8_t* GPIO_base::arp private
Definition at line 230 of file GPIO_NXP.h.
auto_increment
const uint8_t GPIO_base::auto_increment private
Definition at line 231 of file GPIO_NXP.h.
endian
bool GPIO_base::endian private
Definition at line 232 of file GPIO_NXP.h.
intfp
std::unique_ptr<Serial_device> GPIO_base::intfp private
Definition at line 233 of file GPIO_NXP.h.
n_bits
const int GPIO_base::n_bits
Number of IO bits
Definition at line 54 of file GPIO_NXP.h.
n_ports
const int GPIO_base::n_ports
Number of IO ports
Definition at line 57 of file GPIO_NXP.h.
RESET_PIN
int GPIO_base::RESET_PIN = D8 static constexpr private
Definition at line 235 of file GPIO_NXP.h.
The documentation for this class was generated from the following files:
r01device/gpio/GPIO_NXP.h
r01device/gpio/GPIO_NXP.cpp