r01lib: PCF85053A Class Reference
PCF85053A Class Reference
#include <RTC_NXP.h>
Public Types
enum reg_num {
Seconds , Seconds_alarm , Minutes , Minutes_alarm ,
Hours , Hours_alarm , Day_of_the_Week , Day_of_the_Month ,
Month , Year , Control_Register , Status_Register ,
CLKOUT_Control , _2nd_Control_Register , Scratchpad , Version_Register ,
Vendor_ID_Register , Model_Register , Offset , Oscillator ,
Access_config , Sec_timestp , Min_timestp , Hour_timestp ,
DayWk_timestp , DayMon_timestp , Mon_timestp , Year_timestp ,
R_code1 , R_code2
}
Public Types inherited from RTC_NXP
enum board { NONE , ARDUINO_SHIELD }
enum alarm_setting {
SECOND , MINUTE , HOUR , DAY ,
WEEKDAY
}
Public Member Functions
PCF85053A (I2C &interface, uint8_t i2c_address=(0xDE > > 1))
virtual ~PCF85053A ()
void begin (void)
void set (struct tm *now_tm)
bool oscillator_stop (void)
void alarm (alarm_setting digit, int val)
void alarm_clear (void)
void alarm_disable (void)
uint8_t int_clear (void)
time_t rtc_time (void)
time_t time (time_t *tp)
void reg_w (uint8_t reg_adr, uint8_t *data, int size)
void reg_w (uint8_t reg_adr, uint8_t data)
void reg_r (uint8_t reg_adr, uint8_t *data, int size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
uint8_t read_r8 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
Public Member Functions inherited from RTC_NXP
RTC_NXP ()
virtual ~RTC_NXP ()
time_t time (time_t *tp)
Public Member Functions inherited from I2C_device
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
virtual ~I2C_device ()
void repeated_start_enable (bool en=true)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
void write_r16 (uint8_t reg, uint16_t val)
uint16_t read_r16 (uint8_t reg)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
bool ping (void)
uint8_t address (void)
void address_overwrite (uint8_t address)
virtual void ccc_set (CCC ccc, uint8_t data)
virtual uint8_t * ccc_get (CCC ccc, uint8_t *dp, uint8_t length)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Static Private Attributes
static int alarm_offsets [3] = { 1, 3, 5 }
Additional Inherited Members
Static Public Member Functions inherited from I2C_device
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t last=124)
Static Protected Member Functions inherited from RTC_NXP
static uint8_t bcd2dec (uint8_t v)
static uint8_t dec2bcd (uint8_t v)
Protected Attributes inherited from I2C_device
I2C & i2c
uint8_t i2c_addr
Detailed Description
Definition at line 939 of file RTC_NXP.h.
Member Enumeration Documentation
reg_num
enum PCF85053A::reg_num
Name of the PCF85053A registers
Enumerator
Seconds
Seconds_alarm
Minutes
Minutes_alarm
Hours
Hours_alarm
Day_of_the_Week
Day_of_the_Month
Month
Year
Control_Register
Status_Register
CLKOUT_Control
_2nd_Control_Register
Scratchpad
Version_Register
Vendor_ID_Register
Model_Register
Offset
Oscillator
Access_config
Sec_timestp
Min_timestp
Hour_timestp
DayWk_timestp
DayMon_timestp
Mon_timestp
Year_timestp
R_code1
R_code2
Definition at line 943 of file RTC_NXP.h.
Constructor & Destructor Documentation
PCF85053A()
PCF85053A::PCF85053A (I2C & interface, uint8_t i2c_address = (0xDE >> 1))
Create a PCF85053A instance connected to specified I2C pins with specified address
Parameters
wire TwoWire instance
i2c_address I2C-bus address (default: (0xBC>>1))
Definition at line 9 of file PCF85053A.cpp.
References I2C_device::I2C_device().
~PCF85053A()
PCF85053A::~PCF85053A () virtual
Destructor
Definition at line 10 of file PCF85053A.cpp.
Member Function Documentation
alarm()
void PCF85053A::alarm (alarm_setting digit, int val) virtual
Alarm setting
Parameters
digit to specify which parameter to set: SECOND, MINUTE, HOUR in 'enum alarm_setting_85053A'
val Setting value. Set 0x80 to disabling
Implements RTC_NXP.
Definition at line 43 of file PCF85053A.cpp.
References alarm_offsets, bit_op8(), Control_Register, RTC_NXP::dec2bcd(), and reg_w().
alarm_clear()
void PCF85053A::alarm_clear (void) virtual
Alarm clearing
Implements RTC_NXP.
Definition at line 49 of file PCF85053A.cpp.
References alarm_offsets, RTC_NXP::HOUR, RTC_NXP::MINUTE, reg_w(), and RTC_NXP::SECOND.
alarm_disable()
void PCF85053A::alarm_disable (void) virtual
Alarm interrupt disable
Implements RTC_NXP.
Definition at line 56 of file PCF85053A.cpp.
References bit_op8(), and Control_Register.
begin()
void PCF85053A::begin (void) virtual
Initializer but nothing done with this menthod in this version. Don't need to call
Implements RTC_NXP.
Definition at line 12 of file PCF85053A.cpp.
bit_op8()
void PCF85053A::bit_op8 (uint8_t reg, uint8_t mask, uint8_t value) virtual
Register overwriting with bit-mask
Register can be updated by bit level
Parameters
reg register index/address/pointer
mask bit-mask to protect overwriting
value value to overwrite
Reimplemented from I2C_device.
References alarm_offsets.
int_clear()
uint8_t PCF85053A::int_clear (void) virtual
Interrupt clear
Implements RTC_NXP.
Definition at line 61 of file PCF85053A.cpp.
References reg_r(), reg_w(), and Status_Register.
oscillator_stop()
bool PCF85053A::oscillator_stop (void) virtual
Detector for oscillation stop
Returns
true, if the OSF (Oscillator Stop Flag) is set
Implements RTC_NXP.
Definition at line 37 of file PCF85053A.cpp.
References bit_op8(), reg_r(), and Status_Register.
read_r8()
uint8_t PCF85053A::read_r8 (uint8_t reg) virtual
Register read, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
Reimplemented from I2C_device.
reg_r() [1/2]
uint8_t PCF85053A::reg_r (uint8_t reg_adr) virtual
Single register read
Parameters
reg register index/address/pointer
Returns
read data
Reimplemented from I2C_device.
reg_r() [2/2]
void PCF85053A::reg_r (uint8_t reg_adr, uint8_t * data, int size)
Multiple register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
reg_w() [1/2]
void PCF85053A::reg_w (uint8_t reg_adr, uint8_t * data, int size)
Multiple register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
reg_w() [2/2]
void PCF85053A::reg_w (uint8_t reg_adr, uint8_t data) virtual
Single register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Reimplemented from I2C_device.
rtc_time()
time_t PCF85053A::rtc_time (void) virtual
rtc_time
Returns
time_t returns RTC time in time_t format
Implements RTC_NXP.
Definition at line 69 of file PCF85053A.cpp.
References RTC_NXP::bcd2dec(), reg_r(), and Seconds.
set()
void PCF85053A::set (struct tm * now_tm) virtual
set
Parameters
now_tm struct to set calendar and time in RTC
Implements RTC_NXP.
Definition at line 14 of file PCF85053A.cpp.
References RTC_NXP::dec2bcd(), reg_w(), and Seconds.
time()
time_t PCF85053A::time (time_t * tp)
time
"time()" in "time.h" compatible method for RTC
Parameters
tp pointer to time_t variable
Returns
time_t value of current time
write_r8()
void PCF85053A::write_r8 (uint8_t reg, uint8_t val) virtual
Register write, 8 bit
Parameters
reg register index/address/pointer
val data value
Reimplemented from I2C_device.
Member Data Documentation
alarm_offsets
int PCF85053A::alarm_offsets = { 1, 3, 5 } static private
Definition at line 87 of file RTC_NXP.h.
The documentation for this class was generated from the following files:
r01device/rtc/RTC_NXP.h
r01device/rtc/PCF85053A.cpp