r01lib: I2C_device Class Reference
I2C_device Class Reference
#include <I2C_device.h>
Public Member Functions
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
virtual ~I2C_device ()
void repeated_start_enable (bool en=true)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
void write_r16 (uint8_t reg, uint16_t val)
uint8_t read_r8 (uint8_t reg)
uint16_t read_r16 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
bool ping (void)
uint8_t address (void)
void address_overwrite (uint8_t address)
virtual void ccc_set (CCC ccc, uint8_t data)
virtual uint8_t * ccc_get (CCC ccc, uint8_t *dp, uint8_t length)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Static Public Member Functions
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t last=124)
Protected Attributes
I2C & i2c
uint8_t i2c_addr
Private Attributes
bool rs_dis
Detailed Description
GPIO SPI device abstracting class
This class provides common methods for all I2C devices
Author
Tedd OKANO
Released under the MIT license License
I2C_device class
A base class for devices which supports I2C
Definition at line 47 of file I2C_device.h.
Constructor & Destructor Documentation
I2C_device()
I2C_device::I2C_device (I2C & interface, uint8_t i2c_address, bool repeated_start_enable = true)
Create a I2C_device instance with specified address
Parameters
interface I2C instance
i2c_address I2C-bus address
repeated_start_enable repeated-START-condition enable between write and read transaction for register reading. Default: true
Definition at line 16 of file I2C_device.cpp.
References i2c, i2c_addr, repeated_start_enable(), and rs_dis.
~I2C_device()
I2C_device::~I2C_device () virtual
Destructor of I2C_device
Definition at line 20 of file I2C_device.cpp.
Member Function Documentation
address()
uint8_t I2C_device::address (void)
address
Returns
target address in 7bit notation (right justified)
Definition at line 134 of file I2C_device.cpp.
References i2c_addr.
address_overwrite()
void I2C_device::address_overwrite (uint8_t address)
FOR I3C only Target address overwrite
Parameters
address new address given by Dynamic address assignment
Definition at line 139 of file I2C_device.cpp.
References address(), and i2c_addr.
bit_op16()
void I2C_device::bit_op16 (uint8_t reg, uint16_t mask, uint16_t value) virtual
Reimplemented from Serial_device.
Reimplemented in LM75B, P3T1035, P3T1085, P3T1755, P3T2030, PCA8561, PCA9955B, PCA9956B, and PCT2075.
Definition at line 119 of file I2C_device.cpp.
References read_r16(), and write_r16().
bit_op8()
void I2C_device::bit_op8 (uint8_t reg, uint8_t mask, uint8_t value) virtual
Register overwriting with bit-mask
Register can be updated by bit level
Parameters
reg register index/address/pointer
mask bit-mask to protect overwriting
value value to overwrite
Implements Serial_device.
Reimplemented in LM75B, P3T1035, P3T1085, P3T1755, P3T2030, PCA8561, PCA9955B, PCA9956B, PCF85053A, PCF85063A, PCF85063TP, PCF85263A, and PCT2075.
Definition at line 109 of file I2C_device.cpp.
References read_r8(), and write_r8().
ccc_get()
uint8_t * I2C_device::ccc_get (CCC ccc, uint8_t * dp, uint8_t length) virtual
Get Commion Command Code
Parameters
ccc Commion Command Code
dp pointer to data array
length data array length
Returns
pointer to data array
Definition at line 149 of file I2C_device.cpp.
References i2c, and i2c_addr.
ccc_set()
void I2C_device::ccc_set (CCC ccc, uint8_t data) virtual
Set Commion Command Code
Parameters
ccc Commion Command Code
data data for setting
Definition at line 144 of file I2C_device.cpp.
References i2c, and i2c_addr.
ping() [1/2]
bool I2C_device::ping (uint8_t addr) static
ping (class method)
Parameters
target address
Returns
true, if ACKed
References address().
ping() [2/2]
bool I2C_device::ping (void)
ping check device returns ACK
Returns
true if ACKs
Definition at line 129 of file I2C_device.cpp.
References i2c, and i2c_addr.
read_r16()
uint16_t I2C_device::read_r16 (uint8_t reg) virtual
Register read, 16 bit
This 16 bit access may ot be common but it's useful for sensor devices
Parameters
reg register index/address/pointer
Returns
data value
Reimplemented from Serial_device.
Reimplemented in LM75B, P3T1035, P3T1085, P3T1755, P3T2030, and PCT2075.
Definition at line 100 of file I2C_device.cpp.
References reg_r().
read_r8()
uint8_t I2C_device::read_r8 (uint8_t reg) virtual
Register read, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
Implements Serial_device.
Reimplemented in LM75B, P3T1035, P3T1755, P3T2030, PCA8561, PCA9955B, PCA9956B, PCF85053A, PCF85063A, PCF85063TP, PCF85263A, and PCT2075.
Definition at line 95 of file I2C_device.cpp.
References reg_r().
reg_r() [1/2]
uint8_t I2C_device::reg_r (uint8_t reg_adr) virtual
Single register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
read data size
Implements Serial_device.
Reimplemented in LM75B, PCA8561, PCA9955B, PCA9956B, PCF85053A, PCF85063A, PCF85063TP, and PCF85263A.
Definition at line 71 of file I2C_device.cpp.
References rs_dis, rx(), and tx().
reg_r() [2/2]
int I2C_device::reg_r (uint8_t reg_adr, uint8_t * data, uint16_t size) virtual
Multiple register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Implements Serial_device.
Reimplemented in LM75B, PCA8561, PCA9955B, and PCA9956B.
Definition at line 65 of file I2C_device.cpp.
References rs_dis, rx(), and tx().
reg_w() [1/2]
int I2C_device::reg_w (uint8_t reg_adr, const uint8_t * data, uint16_t size) virtual
Multiple register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Implements Serial_device.
Reimplemented in LM75B, and PCA8561.
Definition at line 44 of file I2C_device.cpp.
References tx().
reg_w() [2/2]
int I2C_device::reg_w (uint8_t reg_adr, uint8_t data) virtual
Single register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Implements Serial_device.
Reimplemented in LM75B, PCA8561, PCA9955B, PCA9956B, PCF85053A, PCF85063A, PCF85063TP, and PCF85263A.
Definition at line 55 of file I2C_device.cpp.
References tx().
repeated_start_enable()
void I2C_device::repeated_start_enable (bool en = true)
repeated-START-condition enable
Parameters
en repeated-START-condition enable between write and read transaction for register reading. Default: true
Definition at line 24 of file I2C_device.cpp.
References rs_dis.
rx()
int I2C_device::rx (uint8_t * data, uint16_t size)
Receive data
Parameters
data pointer to data buffer
size data size
Returns
transferred data size
Definition at line 39 of file I2C_device.cpp.
References i2c, and i2c_addr.
scan()
void I2C_device::scan (I2C & target_i2c, uint8_t last = 124) static
scan (class method) thsi is a class-method to scan devices
Parameters
target_i2c I2C instance
last the last address to limit scan range
Definition at line 29 of file I2C_device.cpp.
References I2C::scan().
tx()
int I2C_device::tx (const uint8_t * data, uint16_t size, bool stop = true)
Send data
Parameters
data pointer to data buffer
size data size
stop option: generating STOP-condition after transaction. Defailt: true
Returns
transferred data size or error code in negative number: -1=data too long, -2=NACK for address, -3=NACK for data, -4=Other error, -5=Time out
Definition at line 34 of file I2C_device.cpp.
References i2c, and i2c_addr.
write_r16()
void I2C_device::write_r16 (uint8_t reg, uint16_t val) virtual
Register write, 16 bit
This 16 bit access may ot be common but it's useful for sensor devices
Parameters
reg register index/address/pointer
val data value
Reimplemented from Serial_device.
Reimplemented in LM75B, P3T1035, P3T1085, P3T1755, P3T2030, and PCT2075.
Definition at line 85 of file I2C_device.cpp.
References reg_w().
write_r8()
void I2C_device::write_r8 (uint8_t reg, uint8_t val) virtual
Register write, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
Implements Serial_device.
Reimplemented in LM75B, P3T1035, P3T1755, P3T2030, PCA8561, PCA9955B, PCA9956B, PCF85053A, PCF85063A, PCF85063TP, PCF85263A, and PCT2075.
Definition at line 80 of file I2C_device.cpp.
References reg_w().
Member Data Documentation
i2c
I2C& I2C_device::i2c protected
Definition at line 219 of file I2C_device.h.
i2c_addr
uint8_t I2C_device::i2c_addr protected
Definition at line 220 of file I2C_device.h.
rs_dis
bool I2C_device::rs_dis private
Definition at line 222 of file I2C_device.h.
The documentation for this class was generated from the following files:
r01device/I2C_device.h
r01device/I2C_device.cpp