r01lib: NAFE13388_Base Class Reference
NAFE13388_Base Class Reference
#include <AFE_NXP.h>
Public Types
using raw_t = int32_t
using microvolt_t = double
Public Member Functions
NAFE13388_Base (SPI &spi)
virtual ~NAFE13388_Base ()
virtual void begin (void)
virtual void boot (void)
virtual void reset ()
virtual void board_init (int _pin_nINT, int _pin_DRDY, int _pin_SYN, int _pin_nRESET)
virtual void logical_ch_config (int ch, uint16_t cc0, uint16_t cc1, uint16_t cc2, uint16_t cc3)
template<class T>
T read (int ch, float delay=immidiate_read)
virtual void start (int ch)
template<>
int32_t read (int ch, float delay)
template<>
double read (int ch, float delay)
Public Member Functions inherited from SPI_for_AFE
SPI_for_AFE (SPI &spi)
virtual ~SPI_for_AFE ()
void txrx (uint8_t *data, int size)
void write_r16 (uint16_t reg)
void write_r16 (uint16_t reg, uint16_t val)
uint16_t read_r16 (uint16_t reg)
void write_r24 (uint16_t reg, uint32_t val)
int32_t read_r24 (uint16_t reg)
Public Attributes
int enabled_channels
double coeff_uV [16]
Static Public Attributes
static constexpr float immidiate_read = -1.0
Private Member Functions
void start_and_delay (int ch, float delay)
Detailed Description
Definition at line 49 of file AFE_NXP.h.
Member Typedef Documentation
microvolt_t
using NAFE13388_Base::microvolt_t = double
Definition at line 55 of file AFE_NXP.h.
raw_t
using NAFE13388_Base::raw_t = int32_t
ADC readout types
Definition at line 54 of file AFE_NXP.h.
Constructor & Destructor Documentation
NAFE13388_Base()
NAFE13388_Base::NAFE13388_Base (SPI & spi)
Constructor to create a NAFE13388 instance
NXP Analog Front End class library for MCX
Author
Tedd OKANO
Copyright: 2023 - 2024 Tedd OKANO Released under the MIT license
Definition at line 14 of file AFE_NXP.cpp.
References enabled_channels, and SPI_for_AFE::SPI_for_AFE().
~NAFE13388_Base()
NAFE13388_Base::~NAFE13388_Base () virtual
Destractor
Definition at line 18 of file AFE_NXP.cpp.
Member Function Documentation
begin()
void NAFE13388_Base::begin (void) virtual
Begin the device operation
NAFE13388 initialization. It does following steps (1) Set pins 2 and 3 are input for nINT and nDRDY (2) Set pins 5 and 6 are output and fixed to HIGH for ADC_SYN and ADC_nRESET (3) Call reset() (4) Call boot()
Definition at line 22 of file AFE_NXP.cpp.
References boot(), and reset().
board_init()
void NAFE13388_Base::board_init (int _pin_nINT, int _pin_DRDY, int _pin_SYN, int _pin_nRESET) virtual
Board initialization (initializing control pin state)
Parameters
_pin_nINT pin number for nINT
_pin_DRDY pin number for DRDY
_pin_SYN pin number for SYN
_pin_nRESET pin number for nRESET
Definition at line 47 of file AFE_NXP.cpp.
boot()
void NAFE13388_Base::boot (void) virtual
Set system-level config registers
Definition at line 28 of file AFE_NXP.cpp.
References wait(), and SPI_for_AFE::write_r16().
logical_ch_config()
void NAFE13388_Base::logical_ch_config (int ch, uint16_t cc0, uint16_t cc1, uint16_t cc2, uint16_t cc3) virtual
Configure logical channel
Parameters
ch logical channel number (0 ~ 15)
cc0 16bit value to be set CH_CONFIG0 register (0x20)
cc1 16bit value to be set CH_CONFIG1 register (0x21)
cc2 16bit value to be set CH_CONFIG2 register (0x22)
cc3 16bit value to be set CH_CONFIG3 register (0x23)
Definition at line 56 of file AFE_NXP.cpp.
References coeff_uV, enabled_channels, SPI_for_AFE::read_r16(), and SPI_for_AFE::write_r16().
read() [1/3]
template<> int32_t NAFE13388_Base::read (int ch, float delay)
Definition at line 85 of file AFE_NXP.cpp.
References SPI_for_AFE::read_r24(), and start_and_delay().
read() [2/3]
template<> double NAFE13388_Base::read (int ch, float delay)
Definition at line 92 of file AFE_NXP.cpp.
References coeff_uV, and read().
read() [3/3]
template<class T> T NAFE13388_Base::read (int ch, float delay = immidiate_read)
Read ADC Performs ADC read. If the delay is not given, just the ADC register is read. If the delay is given, measurement is started in this method and read-out after delay. The delay between start and read-out is specified in seconds.
This method need to be called with return type as double value = read<NAFE13388::microvolt_t>(0, 0.01); int32_t value = read<NAFE13388::raw_t>(0, 0.01);
Parameters
ch logical channel number (0 ~ 15)
delay ADC result read-out delay after measurement start if given
Returns
ADC readout value
References immidiate_read.
reset()
void NAFE13388_Base::reset (void) virtual
Issue RESET command
Definition at line 41 of file AFE_NXP.cpp.
References wait(), and SPI_for_AFE::write_r16().
start()
void NAFE13388_Base::start (int ch) virtual
Start ADC
Parameters
ch logical channel number (0 ~ 15)
Definition at line 97 of file AFE_NXP.cpp.
References SPI_for_AFE::write_r16().
start_and_delay()
void NAFE13388_Base::start_and_delay (int ch, float delay) private
Definition at line 103 of file AFE_NXP.cpp.
References start(), and wait().
Member Data Documentation
coeff_uV
double NAFE13388_Base::coeff_uV[16]
Coefficient to convert from ADC read value to micro-volt
Definition at line 126 of file AFE_NXP.h.
enabled_channels
int NAFE13388_Base::enabled_channels
Number of enabled logical channels
Definition at line 123 of file AFE_NXP.h.
immidiate_read
float NAFE13388_Base::immidiate_read = -1.0 static constexpr
Definition at line 56 of file AFE_NXP.h.
The documentation for this class was generated from the following files:
r01device/afe/AFE_NXP.h
r01device/afe/AFE_NXP.cpp