r01lib: AD5161_SPI Class Reference
AD5161_SPI Class Reference
#include <AD5161.h>
Public Member Functions
AD5161_SPI (SPI &interface)
virtual ~AD5161_SPI ()
uint8_t value (uint8_t v)
uint8_t value (void)
void txrx (uint8_t *data, int size)
AD5161_SPI & operator= (uint8_t v)
AD5161_SPI & operator= (AD5161_SPI &rhs)
operator int ()
Public Member Functions inherited from AD5161_base
AD5161_base ()
virtual ~AD5161_base ()
virtual void begin (void)
Private Attributes
SPI & spi
Additional Inherited Members
Protected Attributes inherited from AD5161_base
uint8_t _value
Detailed Description
Definition at line 69 of file AD5161.h.
Constructor & Destructor Documentation
AD5161_SPI()
AD5161_SPI::AD5161_SPI (SPI & interface)
Create a AD5161_SPI instance with specified address
Parameters
interface SPI instance
Definition at line 46 of file AD5161.cpp.
References AD5161_base::AD5161_base(), and spi.
~AD5161_SPI()
AD5161_SPI::~AD5161_SPI () virtual
Definition at line 47 of file AD5161.cpp.
Member Function Documentation
operator int()
AD5161_SPI::operator int ()
A short hand for reading pins
Definition at line 75 of file AD5161.cpp.
References value().
operator=() [1/2]
AD5161_SPI & AD5161_SPI::operator= (AD5161_SPI & rhs)
Definition at line 70 of file AD5161.cpp.
References AD5161_SPI().
operator=() [2/2]
AD5161_SPI & AD5161_SPI::operator= (uint8_t v)
A short hand for setting pins
Definition at line 64 of file AD5161.cpp.
References AD5161_SPI(), and value().
txrx()
void AD5161_SPI::txrx (uint8_t * data, int size)
Send/receive data
Parameters
data pointer to data buffer
size data size
References AD5161_SPI().
value() [1/2]
uint8_t AD5161_SPI::value (uint8_t v)
Set/Get value
Parameters
v for potentiometer position
Returns
potentiometer position
Definition at line 49 of file AD5161.cpp.
References AD5161_base::_value, and spi.
value() [2/2]
uint8_t AD5161_SPI::value (void)
Get value
Returns
potentiometer position
Definition at line 59 of file AD5161.cpp.
References AD5161_base::_value, and value().
Member Data Documentation
spi
SPI& AD5161_SPI::spi private
Definition at line 109 of file AD5161.h.
The documentation for this class was generated from the following files:
r01device/misc/potentiometer/AD5161.h
r01device/misc/potentiometer/AD5161.cpp