r01lib: PCF85263A Class Reference
PCF85263A Class Reference
#include <RTC_NXP.h>
Public Types
enum reg_num {
_100th_seconds , Seconds , Minutes , Hours ,
Days , Weekdays , Months , Years ,
Second_alarm1 , Minute_alarm1 , Hour_alarm1 , Day_alarm1 ,
Month_alarm1 , Minute_alarm2 , Hour_alarm2 , Weekday_alarm2 ,
Alarm_enables , TSR1_seconds , TSR1_minutes , TSR1_hours ,
TSR1_days , TSR1_months , TSR1_years , TSR2_seconds ,
TSR2_minutes , TSR2_hours , TSR2_days , TSR2_months ,
TSR2_years , TSR3_seconds , TSR3_minutes , TSR3_hours ,
TSR3_days , TSR3_months , TSR3_years , TSR_mode ,
Offset , Oscillator , Battery_switch , Pin_IO ,
Function , INTA_enable , INTB_enable , Flags ,
RAM_byte , WatchDog , Stop_enable , Resets ,
Hours_xx_xx_00 = 0x03 , Hours_xx_00_xx , Hours_00_xx_xx , Reserved0 ,
Reserved1 , Second_alm1 , Minute_alm1 , Hr_xx_xx_00_alm1 ,
Hr_xx_00_xx_alm1 , Hr_00_xx_xx_alm1 , Minute_alm2 , Hr_xx_00_alm2 ,
Hr_00_xx_alm2 , TSR1_hr_xx_xx_00 = 0x13 , TSR1_hr_xx_00_xx , TSR1_hr_00_xx_xx ,
Reserved2 , TSR2_hr_xx_xx_00 = 0x19 , TSR2_hr_xx_00_xx , TSR2_hr_00_xx_xx ,
Reserved3 , TSR3_hr_xx_xx_00 = 0x1F , TSR3_hr_xx_00_xx , TSR3_hr_00_xx_xx ,
Reserved4
}
enum alarm_setting_85263A {
SECOND , MINUTE , HOUR , DAY ,
MONTH , MINUTE2 , HOUR2 , WEEKDAY2
}
enum periodic_int_select { DISABLE , EVERY_SECOND , EVERY_MINUTE }
enum inta { INTA_CLKOUT , INTA_BATTERY_MODE_INDICATION , INTA_INTTERRUPT , INTA_HIGH_Z }
enum intb { INTB_DISABLE , INTB_INTTERRUPT , INTB_CLKOUT , INTB_INPUT_MODE }
enum ts_in {
TS_PULLUP_80K = 0x00 , TS_PULLUP_40K = 0x40 , TSL_ACTIVE_HIGH = 0x00 , TSL_ACTIVE_LOW = 0x20 ,
TSIM_CMOS = 0x00 , TSIM_MECHANICAL = 0x10
}
enum int_out_sel { INT_A , INT_B }
Public Types inherited from RTC_NXP
enum board { NONE , ARDUINO_SHIELD }
enum alarm_setting {
SECOND , MINUTE , HOUR , DAY ,
WEEKDAY
}
Public Member Functions
PCF85263A (I2C &interface, uint8_t i2c_address=(0xA2 > > 1))
virtual ~PCF85263A ()
void begin (void)
void set (struct tm *now_tm)
bool oscillator_stop (void)
void alarm (alarm_setting digit, int val)
void alarm (alarm_setting digit, int val, int int_sel)
void alarm (alarm_setting_85263A digit, int val, int int_sel=0)
void alarm_clear (void)
void alarm_disable (void)
uint8_t int_clear (void)
time_t rtc_time (void)
void periodic_interrupt_enable (periodic_int_select sel, int int_sel=0)
void pin_congfig (inta cfg_a, intb cfg_b)
void ts_congfig (int setting)
time_t timestamp (int num)
time_t time (time_t *tp)
void reg_w (uint8_t reg_adr, uint8_t *data, int size)
void reg_w (uint8_t reg_adr, uint8_t data)
void reg_r (uint8_t reg_adr, uint8_t *data, int size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
uint8_t read_r8 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
Public Member Functions inherited from RTC_NXP
RTC_NXP ()
virtual ~RTC_NXP ()
time_t time (time_t *tp)
Public Member Functions inherited from I2C_device
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
virtual ~I2C_device ()
void repeated_start_enable (bool en=true)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
void write_r16 (uint8_t reg, uint16_t val)
uint16_t read_r16 (uint8_t reg)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
bool ping (void)
uint8_t address (void)
void address_overwrite (uint8_t address)
virtual void ccc_set (CCC ccc, uint8_t data)
virtual uint8_t * ccc_get (CCC ccc, uint8_t *dp, uint8_t length)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Private Member Functions
void set_alarm (int digit, int val, int int_sel)
Additional Inherited Members
Static Public Member Functions inherited from I2C_device
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t last=124)
Static Protected Member Functions inherited from RTC_NXP
static uint8_t bcd2dec (uint8_t v)
static uint8_t dec2bcd (uint8_t v)
Protected Attributes inherited from I2C_device
I2C & i2c
uint8_t i2c_addr
Detailed Description
Definition at line 698 of file RTC_NXP.h.
Member Enumeration Documentation
alarm_setting_85263A
enum PCF85263A::alarm_setting_85263A
Alarm setting digit selection descriptor
Enumerator
SECOND
MINUTE
HOUR
DAY
MONTH
MINUTE2
HOUR2
WEEKDAY2
Definition at line 724 of file RTC_NXP.h.
int_out_sel
enum PCF85263A::int_out_sel
Interrupt output selector
Enumerator
INT_A
INT_B
Definition at line 769 of file RTC_NXP.h.
inta
enum PCF85263A::inta
INT_A pin setting descriptor
Enumerator
INTA_CLKOUT
INTA_BATTERY_MODE_INDICATION
INTA_INTTERRUPT
INTA_HIGH_Z
Definition at line 743 of file RTC_NXP.h.
intb
enum PCF85263A::intb
INT_B pin setting descriptor
Enumerator
INTB_DISABLE
INTB_INTTERRUPT
INTB_CLKOUT
INTB_INPUT_MODE
Definition at line 751 of file RTC_NXP.h.
periodic_int_select
enum PCF85263A::periodic_int_select
Periodic interrupt selection descriptor
Enumerator
DISABLE
EVERY_SECOND
EVERY_MINUTE
Definition at line 736 of file RTC_NXP.h.
reg_num
enum PCF85263A::reg_num
Name of the PCF85263A registers
Enumerator
_100th_seconds
Seconds
Minutes
Hours
Days
Weekdays
Months
Years
Second_alarm1
Minute_alarm1
Hour_alarm1
Day_alarm1
Month_alarm1
Minute_alarm2
Hour_alarm2
Weekday_alarm2
Alarm_enables
TSR1_seconds
TSR1_minutes
TSR1_hours
TSR1_days
TSR1_months
TSR1_years
TSR2_seconds
TSR2_minutes
TSR2_hours
TSR2_days
TSR2_months
TSR2_years
TSR3_seconds
TSR3_minutes
TSR3_hours
TSR3_days
TSR3_months
TSR3_years
TSR_mode
Offset
Oscillator
Battery_switch
Pin_IO
Function
INTA_enable
INTB_enable
Flags
RAM_byte
WatchDog
Stop_enable
Resets
Hours_xx_xx_00
Hours_xx_00_xx
Hours_00_xx_xx
Reserved0
Reserved1
Second_alm1
Minute_alm1
Hr_xx_xx_00_alm1
Hr_xx_00_xx_alm1
Hr_00_xx_xx_alm1
Minute_alm2
Hr_xx_00_alm2
Hr_00_xx_alm2
TSR1_hr_xx_xx_00
TSR1_hr_xx_00_xx
TSR1_hr_00_xx_xx
Reserved2
TSR2_hr_xx_xx_00
TSR2_hr_xx_00_xx
TSR2_hr_00_xx_xx
Reserved3
TSR3_hr_xx_xx_00
TSR3_hr_xx_00_xx
TSR3_hr_00_xx_xx
Reserved4
Definition at line 702 of file RTC_NXP.h.
ts_in
enum PCF85263A::ts_in
Timestamp pin input setting descriptor
Enumerator
TS_PULLUP_80K
TS_PULLUP_40K
TSL_ACTIVE_HIGH
TSL_ACTIVE_LOW
TSIM_CMOS
TSIM_MECHANICAL
Definition at line 759 of file RTC_NXP.h.
Constructor & Destructor Documentation
PCF85263A()
PCF85263A::PCF85263A (I2C & interface, uint8_t i2c_address = (0xA2 >> 1))
Create a PCF85263A instance connected to specified I2C pins with specified address
Parameters
wire TwoWire instance
i2c_address I2C-bus address (default: (0xBC>>1))
Definition at line 9 of file PCF85263A.cpp.
References I2C_device::I2C_device().
~PCF85263A()
PCF85263A::~PCF85263A () virtual
Destructor
Definition at line 13 of file PCF85263A.cpp.
Member Function Documentation
alarm() [1/3]
void PCF85263A::alarm (alarm_setting digit, int val) virtual
Alarm setting
Parameters
digit to specify which parameter to set: SECOND, MINUTE, HOUR, DAY, WEEKDAY in 'enum alarm_setting'
val Setting value. Set 0x80 to disabling
Implements RTC_NXP.
Definition at line 52 of file PCF85263A.cpp.
References alarm().
alarm() [2/3]
void PCF85263A::alarm (alarm_setting digit, int val, int int_sel)
Alarm setting
Parameters
digit to specify which parameter to set: SECOND, MINUTE, HOUR, DAY, WEEKDAY in 'enum alarm_setting'
val Setting value. Set 0x80 to disabling
int_sel Interrupt output selector.) for INT_A, 1 for INT_B
Definition at line 57 of file PCF85263A.cpp.
References set_alarm(), and RTC_NXP::WEEKDAY.
alarm() [3/3]
void PCF85263A::alarm (alarm_setting_85263A digit, int val, int int_sel = 0)
Alarm setting
Parameters
digit to specify which parameter to set: SECOND, MINUTE, HOUR, DAY, WEEKDAY in 'enum alarm_setting'
val Setting value. Set 0x80 to disabling
Definition at line 67 of file PCF85263A.cpp.
References set_alarm().
alarm_clear()
void PCF85263A::alarm_clear (void) virtual
Alarm clearing
Implements RTC_NXP.
Definition at line 85 of file PCF85263A.cpp.
References Alarm_enables, and reg_w().
alarm_disable()
void PCF85263A::alarm_disable (void) virtual
Alarm interrupt disable
Implements RTC_NXP.
Definition at line 90 of file PCF85263A.cpp.
References bit_op8(), INTA_enable, and INTB_enable.
begin()
void PCF85263A::begin (void) virtual
Initializer but nothing done with this menthod in this version. Don't need to call
Implements RTC_NXP.
Definition at line 17 of file PCF85263A.cpp.
bit_op8()
void PCF85263A::bit_op8 (uint8_t reg, uint8_t mask, uint8_t value) virtual
Register overwriting with bit-mask
Register can be updated by bit level
Parameters
reg register index/address/pointer
mask bit-mask to protect overwriting
value value to overwrite
Reimplemented from I2C_device.
int_clear()
uint8_t PCF85263A::int_clear (void) virtual
Interrupt clear
Implements RTC_NXP.
Definition at line 96 of file PCF85263A.cpp.
References Flags, reg_r(), and reg_w().
oscillator_stop()
bool PCF85263A::oscillator_stop (void) virtual
Detector for oscillation stop
Returns
true, if the OSF (Oscillator Stop Flag) is set
Implements RTC_NXP.
Definition at line 47 of file PCF85263A.cpp.
References reg_r(), and Seconds.
periodic_interrupt_enable()
void PCF85263A::periodic_interrupt_enable (periodic_int_select sel, int int_sel = 0)
Enabling every second/minute interrupt
Parameters
sel choose DISABLE, EVERY_SECOND or EVERY_MINUTE in 'enum periodic_int_select'
Definition at line 122 of file PCF85263A.cpp.
References bit_op8(), Function, and INTA_enable.
pin_congfig()
void PCF85263A::pin_congfig (inta cfg_a, intb cfg_b)
Pin configuration
Parameters
cfg_a To choose INT_A pin congiguration: Use CLKOUT, BATTERY_MODE_INDICATION, INTTERRUPT or HIGH_Z
cfg_b To choose INT_A pin congiguration: Use DISABLE, INTTERRUPT, CLKOUT or INPUTMODE
Definition at line 130 of file PCF85263A.cpp.
References bit_op8(), and Pin_IO.
read_r8()
uint8_t PCF85263A::read_r8 (uint8_t reg) virtual
Register read, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
Reimplemented from I2C_device.
reg_r() [1/2]
uint8_t PCF85263A::reg_r (uint8_t reg_adr) virtual
Single register read
Parameters
reg register index/address/pointer
Returns
read data
Reimplemented from I2C_device.
reg_r() [2/2]
void PCF85263A::reg_r (uint8_t reg_adr, uint8_t * data, int size)
Multiple register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
reg_w() [1/2]
void PCF85263A::reg_w (uint8_t reg_adr, uint8_t * data, int size)
Multiple register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
reg_w() [2/2]
void PCF85263A::reg_w (uint8_t reg_adr, uint8_t data) virtual
Single register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Reimplemented from I2C_device.
rtc_time()
time_t PCF85263A::rtc_time (void) virtual
rtc_time
Returns
time_t returns RTC time in time_t format
Implements RTC_NXP.
Definition at line 104 of file PCF85263A.cpp.
References _100th_seconds, RTC_NXP::bcd2dec(), and reg_r().
set()
void PCF85263A::set (struct tm * now_tm) virtual
set
Parameters
now_tm struct to set calendar and time in RTC
Implements RTC_NXP.
Definition at line 21 of file PCF85263A.cpp.
References RTC_NXP::dec2bcd(), reg_w(), and Stop_enable.
set_alarm()
void PCF85263A::set_alarm (int digit, int val, int int_sel) private
Definition at line 72 of file PCF85263A.cpp.
References Alarm_enables, bit_op8(), RTC_NXP::dec2bcd(), INTA_enable, reg_w(), and Second_alarm1.
time()
time_t PCF85263A::time (time_t * tp)
time
"time()" in "time.h" compatible method for RTC
Parameters
tp pointer to time_t variable
Returns
time_t value of current time
timestamp()
time_t PCF85263A::timestamp (int num)
Timestamp register read
Parameters
num timestamp index
Definition at line 141 of file PCF85263A.cpp.
References RTC_NXP::bcd2dec(), reg_r(), and TSR1_seconds.
ts_congfig()
void PCF85263A::ts_congfig (int setting)
Timestamp pin configuration
Parameters
setting To choose options: Compose value by ORing next constants: TS_PULLUP_80K, TS_PULLUP_40K, TSL_ACTIVE_HIGH, TSL_ACTIVE_LOW, TSIM_CMOS and TSIM_MECHANICAL
Definition at line 135 of file PCF85263A.cpp.
References bit_op8(), INTA_enable, and Pin_IO.
write_r8()
void PCF85263A::write_r8 (uint8_t reg, uint8_t val) virtual
Register write, 8 bit
Parameters
reg register index/address/pointer
val data value
Reimplemented from I2C_device.
The documentation for this class was generated from the following files:
r01device/rtc/RTC_NXP.h
r01device/rtc/PCF85263A.cpp