r01lib: AD5161_I2C Class Reference
AD5161_I2C Class Reference
#include <AD5161.h>
Public Member Functions
AD5161_I2C (I2C &interface, uint8_t i2c_address=(0x5A > > 1))
virtual ~AD5161_I2C ()
void value (uint8_t v)
uint8_t value (void)
AD5161_I2C & operator= (uint8_t v)
AD5161_I2C & operator= (AD5161_I2C &rhs)
operator int ()
Public Member Functions inherited from AD5161_base
AD5161_base ()
virtual ~AD5161_base ()
virtual void begin (void)
Public Member Functions inherited from I2C_device
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
virtual ~I2C_device ()
void repeated_start_enable (bool en=true)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
void write_r16 (uint8_t reg, uint16_t val)
uint8_t read_r8 (uint8_t reg)
uint16_t read_r16 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
bool ping (void)
uint8_t address (void)
void address_overwrite (uint8_t address)
virtual void ccc_set (CCC ccc, uint8_t data)
virtual uint8_t * ccc_get (CCC ccc, uint8_t *dp, uint8_t length)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Additional Inherited Members
Static Public Member Functions inherited from I2C_device
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t last=124)
Protected Attributes inherited from AD5161_base
uint8_t _value
Protected Attributes inherited from I2C_device
I2C & i2c
uint8_t i2c_addr
Detailed Description
AD5161 class
Definition at line 36 of file AD5161.h.
Constructor & Destructor Documentation
AD5161_I2C()
AD5161_I2C::AD5161_I2C (I2C & interface, uint8_t i2c_address = (0x5A >> 1))
Create a AD5161_I2C instance with specified address
Parameters
interface I2C instance
i2c_address I2C-bus address (default: (0xA2>>1))
Definition at line 13 of file AD5161.cpp.
References AD5161_base::AD5161_base(), and I2C_device::I2C_device().
~AD5161_I2C()
AD5161_I2C::~AD5161_I2C () virtual
Definition at line 14 of file AD5161.cpp.
Member Function Documentation
operator int()
AD5161_I2C::operator int ()
A short hand for reading pins
Definition at line 40 of file AD5161.cpp.
References value().
operator=() [1/2]
AD5161_I2C & AD5161_I2C::operator= (AD5161_I2C & rhs)
Definition at line 35 of file AD5161.cpp.
References AD5161_I2C().
operator=() [2/2]
AD5161_I2C & AD5161_I2C::operator= (uint8_t v)
A short hand for setting pins
Definition at line 29 of file AD5161.cpp.
References AD5161_I2C(), and value().
value() [1/2]
void AD5161_I2C::value (uint8_t v)
Set value
Parameters
v for potentiometer position
Definition at line 16 of file AD5161.cpp.
References I2C_device::write_r8().
value() [2/2]
uint8_t AD5161_I2C::value (void)
Get value
Returns
potentiometer position
Definition at line 21 of file AD5161.cpp.
References I2C_device::rx().
The documentation for this class was generated from the following files:
r01device/misc/potentiometer/AD5161.h
r01device/misc/potentiometer/AD5161.cpp