r01lib: DigitalInOut Class Reference
DigitalInOut Class Reference
#include <io.h>
Public Types
enum direction { INPUT = kGPIO_DigitalInput , OUTPUT = kGPIO_DigitalOutput }
enum PinMode { PullNone = 0x0 , PullUp = 0x1 , PullDown = 0x2 , OpenDrain = 0x8 }
Public Member Functions
DigitalInOut (uint8_t pin_num, bool direction=kGPIO_DigitalInput, bool value=0, int pin_mode=PullNone)
virtual ~DigitalInOut ()
void value (bool value)
bool value (void)
void output (void)
void input (void)
void pin_mux (int mux)
void mode (int pin_mode)
uint32_t mode (void)
DigitalInOut & operator= (bool v)
DigitalInOut & operator= (DigitalInOut &rhs)
operator bool ()
Public Member Functions inherited from Obj
Obj (bool done=false)
virtual ~Obj ()
Protected Member Functions
void direction (bool dir)
Protected Attributes
uint8_t _pn
GPIO_Type * gpio_n
PORT_Type * port_n
uint8_t gpio_pin
Private Attributes
bool _dir
bool _value
Detailed Description
DigitalInOut class
A class for operating GPIO easy
Definition at line 667 of file io.h.
Member Enumeration Documentation
direction
enum DigitalInOut::direction
Enumerator
INPUT
OUTPUT
Definition at line 670 of file io.h.
PinMode
enum DigitalInOut::PinMode
Enumerator
PullNone
PullUp
PullDown
OpenDrain
Definition at line 675 of file io.h.
Constructor & Destructor Documentation
DigitalInOut()
DigitalInOut::DigitalInOut (uint8_t pin_num, bool direction = kGPIO_DigitalInput, bool value = 0, int pin_mode = PullNone)
Create a DigitalInOut instance with specified pins
Parameters
pin_num pin number
direction (option) direction setting
value (option) default value for output
pin_mode (option) PullUp, PullDown, PullNone, OpenDrain
Definition at line 419 of file io.cpp.
References _dir, _pn, _value, _gpio_pin::base, gpio_n, gpio_pin, gpio_type, mode(), Obj::Obj(), port_n, port_type, and value().
~DigitalInOut()
DigitalInOut::~DigitalInOut () virtual
Destractor
Definition at line 437 of file io.cpp.
Member Function Documentation
direction()
void DigitalInOut::direction (bool dir) protected
Definition at line 473 of file io.cpp.
References _value, gpio_n, and gpio_pin.
input()
void DigitalInOut::input (void)
Pin direction to set as in
Definition at line 467 of file io.cpp.
References _dir, and INPUT.
mode() [1/2]
void DigitalInOut::mode (int pin_mode)
Pin mode setting
Parameters
pin_mode PullUp, PullDown, PullNone, OpenDrain
Definition at line 484 of file io.cpp.
References gpio_pin, OpenDrain, port_n, PORT_SetPinOpenDrain(), PORT_SetPinPullUpDown(), PullDown, and PullUp.
mode() [2/2]
uint32_t DigitalInOut::mode (void)
Definition at line 490 of file io.cpp.
References gpio_pin, PORT_GetPinMode(), and port_n.
operator bool()
DigitalInOut::operator bool ()
A short hand for reading pins
Definition at line 506 of file io.cpp.
References value().
operator=() [1/2]
DigitalInOut & DigitalInOut::operator= (bool v)
A short hand for setting pins
Definition at line 495 of file io.cpp.
References DigitalInOut(), and value().
operator=() [2/2]
DigitalInOut & DigitalInOut::operator= (DigitalInOut & rhs)
Definition at line 501 of file io.cpp.
References DigitalInOut().
output()
void DigitalInOut::output (void)
Pin direction to set as output
Definition at line 461 of file io.cpp.
References _dir, and OUTPUT.
pin_mux()
void DigitalInOut::pin_mux (int mux)
Pin mux setting This interface is provided to other class drivers to change pin config dynamically
Definition at line 479 of file io.cpp.
References gpio_pin, and port_n.
value() [1/2]
void DigitalInOut::value (bool value)
Pin output seting
Parameters
value setting output
Definition at line 439 of file io.cpp.
References _dir, _pn, _value, gpio_n, gpio_pin, and value().
value() [2/2]
bool DigitalInOut::value (void)
Pin input state read
Returns
pin state
Definition at line 450 of file io.cpp.
References _dir, _pn, _value, gpio_n, and gpio_pin.
Member Data Documentation
_dir
bool DigitalInOut::_dir private
Definition at line 745 of file io.h.
_pn
uint8_t DigitalInOut::_pn protected
Definition at line 739 of file io.h.
_value
bool DigitalInOut::_value private
Definition at line 746 of file io.h.
gpio_n
GPIO_Type* DigitalInOut::gpio_n protected
Definition at line 740 of file io.h.
gpio_pin
uint8_t DigitalInOut::gpio_pin protected
Definition at line 742 of file io.h.
port_n
PORT_Type* DigitalInOut::port_n protected
Definition at line 741 of file io.h.
The documentation for this class was generated from the following files:
r01lib/io.h
r01lib/io.cpp