r01lib: BusInOut Class Reference
BusInOut Class Reference
#include <BusInOut.h>
Public Types
enum direction { INPUT = DigitalInOut::INPUT , OUTPUT = DigitalInOut::OUTPUT }
Public Member Functions
BusInOut (uint8_t bit0=nc, uint8_t bit1=nc, uint8_t bit2=nc, uint8_t bit3=nc, uint8_t bit4=nc, uint8_t bit5=nc, uint8_t bit6=nc, uint8_t bit7=nc)
virtual ~BusInOut ()
virtual void config (int conf)
virtual void value (uint8_t v)
virtual uint8_t value (void)
BusInOut & operator= (uint8_t v)
BusInOut & operator= (BusInOut &rhs)
operator int ()
Static Public Attributes
static constexpr uint8_t nc = 0xFF
Private Attributes
DigitalInOut * _bits [8]
uint8_t _width
uint8_t _mode
Detailed Description
BusInOut class
This class can be inherited. When the "operator=" need to be used in inherited class, use "using BusInOut::operator=;" in that class.
Definition at line 22 of file BusInOut.h.
Member Enumeration Documentation
direction
enum BusInOut::direction
Enumerator
INPUT
OUTPUT
Definition at line 24 of file BusInOut.h.
Constructor & Destructor Documentation
BusInOut()
BusInOut::BusInOut (uint8_t bit0 = nc, uint8_t bit1 = nc, uint8_t bit2 = nc, uint8_t bit3 = nc, uint8_t bit4 = nc, uint8_t bit5 = nc, uint8_t bit6 = nc, uint8_t bit7 = nc)
Create a BusInOut instance with specified pins
Parameters
bit<n> pin number to connect bus bit<n> (0-13, nc)
Note
define pins from lower to upper. No need to define upper bits if those are not be used
Definition at line 10 of file BusInOut.cpp.
References _bits, _width, and nc.
~BusInOut()
BusInOut::~BusInOut () virtual
Destractor
Definition at line 40 of file BusInOut.cpp.
References _bits, and _width.
Member Function Documentation
config()
void BusInOut::config (int conf) virtual
Configure BusInOut IO direction
Parameters
conf INPUT or OUTPUT (defined in Arduino.h)
Reimplemented in BusIn, and BusOut.
Definition at line 49 of file BusInOut.cpp.
References _bits, _mode, _width, and DigitalInOut::INPUT.
operator int()
BusInOut::operator int ()
A short hand for reading pins
Definition at line 98 of file BusInOut.cpp.
References value().
operator=() [1/2]
BusInOut & BusInOut::operator= (BusInOut & rhs)
Definition at line 93 of file BusInOut.cpp.
References BusInOut().
operator=() [2/2]
BusInOut & BusInOut::operator= (uint8_t v)
A short hand for setting pins
Definition at line 87 of file BusInOut.cpp.
References BusInOut(), and value().
value() [1/2]
void BusInOut::value (uint8_t v) virtual
Output a value to BusInOut pins
Parameters
v value to be set to pins
Definition at line 65 of file BusInOut.cpp.
References _bits, and _width.
value() [2/2]
uint8_t BusInOut::value (void) virtual
Input a value from BusInOut pins
Returns
value read from pins
Definition at line 74 of file BusInOut.cpp.
References _bits, and _width.
Member Data Documentation
_bits
DigitalInOut* BusInOut::_bits[8] private
Definition at line 80 of file BusInOut.h.
_mode
uint8_t BusInOut::_mode private
Definition at line 82 of file BusInOut.h.
_width
uint8_t BusInOut::_width private
Definition at line 81 of file BusInOut.h.
nc
uint8_t BusInOut::nc = 0xFF static constexpr
To define non-connected pin, use BusInOut::nc
Definition at line 30 of file BusInOut.h.
The documentation for this class was generated from the following files:
r01lib/BusInOut.h
r01lib/BusInOut.cpp