r01lib: PCF85063A Class Reference
PCF85063A Class Reference
#include <RTC_NXP.h>
Public Types
enum reg_num {
Control_1 , Control_2 , Offset , RAM_byte ,
Seconds , Minutes , Hours , Days ,
Weekdays , Months , Years , Second_alarm ,
Minute_alarm , Hour_alarm , Day_alarm , Weekday_alarm ,
Timer_value , Timer_mode
}
Public Types inherited from PCF85063_base
enum reg_num {
Control_1 , Control_2 , Offset , RAM_byte ,
Seconds , Minutes , Hours , Days ,
Weekdays , Months , Years , Second_alarm ,
Minute_alarm , Hour_alarm , Day_alarm , Weekday_alarm ,
Timer_value , Timer_mode
}
Public Types inherited from RTC_NXP
enum board { NONE , ARDUINO_SHIELD }
enum alarm_setting {
SECOND , MINUTE , HOUR , DAY ,
WEEKDAY
}
Public Member Functions
PCF85063A (I2C &interface, uint8_t i2c_address=(0xA2 > > 1))
virtual ~PCF85063A ()
time_t time (time_t *tp)
void begin (void)
void set (struct tm *now_tm)
bool oscillator_stop (void)
void alarm (alarm_setting digit, int val)
void alarm_clear (void)
void alarm_disable (void)
uint8_t int_clear (void)
float timer (float period)
void reg_w (uint8_t reg_adr, uint8_t *data, int size)
void reg_w (uint8_t reg_adr, uint8_t data)
void reg_r (uint8_t reg_adr, uint8_t *data, int size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
uint8_t read_r8 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
Public Member Functions inherited from PCF85063_base
PCF85063_base ()
virtual ~PCF85063_base ()
float timer (float period)
Public Member Functions inherited from RTC_NXP
RTC_NXP ()
virtual ~RTC_NXP ()
time_t time (time_t *tp)
Public Member Functions inherited from I2C_device
I2C_device (I2C &interface, uint8_t i2c_address, bool repeated_start_enable=true)
virtual ~I2C_device ()
void repeated_start_enable (bool en=true)
int tx (const uint8_t *data, uint16_t size, bool stop=true)
int rx (uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
void write_r16 (uint8_t reg, uint16_t val)
uint16_t read_r16 (uint8_t reg)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
bool ping (void)
uint8_t address (void)
void address_overwrite (uint8_t address)
virtual void ccc_set (CCC ccc, uint8_t data)
virtual uint8_t * ccc_get (CCC ccc, uint8_t *dp, uint8_t length)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Private Member Functions
void _reg_w (uint8_t reg, uint8_t *vp, int len)
void _reg_r (uint8_t reg, uint8_t *vp, int len)
void _reg_w (uint8_t reg, uint8_t val)
uint8_t _reg_r (uint8_t reg)
void _bit_op8 (uint8_t reg, uint8_t mask, uint8_t val)
Additional Inherited Members
Static Public Member Functions inherited from I2C_device
static bool ping (uint8_t addr)
static void scan (I2C &target_i2c, uint8_t last=124)
Protected Member Functions inherited from PCF85063_base
time_t rtc_time (void)
Static Protected Member Functions inherited from RTC_NXP
static uint8_t bcd2dec (uint8_t v)
static uint8_t dec2bcd (uint8_t v)
Protected Attributes inherited from I2C_device
I2C & i2c
uint8_t i2c_addr
Detailed Description
PCF85063A class
PCF85063A class driver
Definition at line 435 of file RTC_NXP.h.
Member Enumeration Documentation
reg_num
enum PCF85063A::reg_num
Name of the PCF85063A registers
Enumerator
Control_1
Control_2
Offset
RAM_byte
Seconds
Minutes
Hours
Days
Weekdays
Months
Years
Second_alarm
Minute_alarm
Hour_alarm
Day_alarm
Weekday_alarm
Timer_value
Timer_mode
Definition at line 450 of file RTC_NXP.h.
Constructor & Destructor Documentation
PCF85063A()
PCF85063A::PCF85063A (I2C & interface, uint8_t i2c_address = (0xA2 >> 1))
Create a PCF85063A instance connected to specified I2C pins with specified address
Parameters
wire TwoWire instance
i2c_address I2C-bus address (default: (0xBC>>1))
Definition at line 126 of file PCF85063A.cpp.
References I2C_device::I2C_device().
~PCF85063A()
PCF85063A::~PCF85063A () virtual
Destructor
Definition at line 130 of file PCF85063A.cpp.
Member Function Documentation
_bit_op8()
void PCF85063A::_bit_op8 (uint8_t reg, uint8_t mask, uint8_t val) private virtual
Proxy method for interface
Implements PCF85063_base.
Definition at line 154 of file PCF85063A.cpp.
References bit_op8().
_reg_r() [1/2]
uint8_t PCF85063A::_reg_r (uint8_t reg) private virtual
Proxy method for interface
Implements PCF85063_base.
Definition at line 149 of file PCF85063A.cpp.
References reg_r().
_reg_r() [2/2]
void PCF85063A::_reg_r (uint8_t reg, uint8_t * vp, int len) private virtual
Proxy method for interface
Implements PCF85063_base.
Definition at line 139 of file PCF85063A.cpp.
References reg_r().
_reg_w() [1/2]
void PCF85063A::_reg_w (uint8_t reg, uint8_t * vp, int len) private virtual
Proxy method for interface
Implements PCF85063_base.
Definition at line 134 of file PCF85063A.cpp.
References reg_w().
_reg_w() [2/2]
void PCF85063A::_reg_w (uint8_t reg, uint8_t val) private virtual
Proxy method for interface
Implements PCF85063_base.
Definition at line 144 of file PCF85063A.cpp.
References reg_w().
alarm()
void PCF85063A::alarm (alarm_setting digit, int val) virtual
Alarm setting
Parameters
digit to specify which parameter to set: SECOND, MINUTE, HOUR, DAY, WEEKDAY in 'enum alarm_setting'
val Setting value. Set 0x80 to disabling
Reimplemented from PCF85063_base.
alarm_clear()
void PCF85063A::alarm_clear (void) virtual
Alarm clearing
Reimplemented from PCF85063_base.
alarm_disable()
void PCF85063A::alarm_disable (void) virtual
Alarm interrupt disable
Reimplemented from PCF85063_base.
begin()
void PCF85063A::begin (void) virtual
Initializer but nothing done with this menthod in this version. Don't need to call
Reimplemented from PCF85063_base.
Reimplemented in PCF85063TP.
bit_op8()
void PCF85063A::bit_op8 (uint8_t reg, uint8_t mask, uint8_t value) virtual
Register overwriting with bit-mask
Register can be updated by bit level
Parameters
reg register index/address/pointer
mask bit-mask to protect overwriting
value value to overwrite
Reimplemented from I2C_device.
Reimplemented in PCF85063TP.
int_clear()
uint8_t PCF85063A::int_clear (void) virtual
Interrupt clear
Reimplemented from PCF85063_base.
oscillator_stop()
bool PCF85063A::oscillator_stop (void) virtual
Detector for oscillation stop
Returns
true, if the OSF (Oscillator Stop Flag) is set
Reimplemented from PCF85063_base.
Reimplemented in PCF85063TP.
read_r8()
uint8_t PCF85063A::read_r8 (uint8_t reg) virtual
Register read, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
Reimplemented from I2C_device.
Reimplemented in PCF85063TP.
reg_r() [1/2]
uint8_t PCF85063A::reg_r (uint8_t reg_adr) virtual
Single register read
Parameters
reg register index/address/pointer
Returns
read data
Reimplemented from I2C_device.
Reimplemented in PCF85063TP.
reg_r() [2/2]
void PCF85063A::reg_r (uint8_t reg_adr, uint8_t * data, int size)
Multiple register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
reg_w() [1/2]
void PCF85063A::reg_w (uint8_t reg_adr, uint8_t * data, int size)
Multiple register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
reg_w() [2/2]
void PCF85063A::reg_w (uint8_t reg_adr, uint8_t data) virtual
Single register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Reimplemented from I2C_device.
Reimplemented in PCF85063TP.
set()
void PCF85063A::set (struct tm * now_tm) virtual
set
Parameters
now_tm struct to set calendar and time in RTC
Reimplemented from PCF85063_base.
Reimplemented in PCF85063TP.
time()
time_t PCF85063A::time (time_t * tp)
time
"time()" in "time.h" compatible method for RTC
Parameters
tp pointer to time_t variable
Returns
time_t value of current time
timer()
float PCF85063A::timer (float period)
Timer setting
Parameters
period timer interval in second
Returns
actual timer set value in second
write_r8()
void PCF85063A::write_r8 (uint8_t reg, uint8_t val) virtual
Register write, 8 bit
Parameters
reg register index/address/pointer
val data value
Reimplemented from I2C_device.
Reimplemented in PCF85063TP.
The documentation for this class was generated from the following files:
r01device/rtc/RTC_NXP.h
r01device/rtc/PCF85063A.cpp