r01lib: I2C Class Reference
I2C Class Reference
#include <i2c.h>
Public Types
enum STOP_CONDITION { STOP = true , NO_STOP = false }
enum FREQ { FREQ = 400000UL }
typedef void(* err_cb_ptr) (status_t status, uint8_t address)
Public Member Functions
I2C (int sda, int scl, bool no_hw=false)
virtual ~I2C ()
virtual void frequency (uint32_t frequency)
virtual void pullup (bool enable)
virtual status_t reg_write (uint8_t targ, uint8_t reg, const uint8_t *dp, int length)
virtual status_t reg_write (uint8_t targ, uint8_t reg, uint8_t data)
virtual status_t reg_read (uint8_t targ, uint8_t reg, uint8_t *dp, int length)
virtual uint8_t reg_read (uint8_t targ, uint8_t reg)
virtual status_t write (uint8_t address, const uint8_t *dp, int length, bool stop=STOP)
virtual status_t write (uint8_t targ, uint8_t data, bool stop=STOP)
virtual status_t read (uint8_t address, uint8_t *dp, int length, bool stop=STOP)
virtual uint8_t read (uint8_t targ, bool stop=STOP)
virtual err_cb_ptr err_callback (err_cb_ptr)
virtual bool ping (uint8_t addr)
virtual void scan (uint8_t start, uint8_t last, bool *result)
virtual void scan (uint8_t start, uint8_t last)
virtual void scan (uint8_t last=124)
virtual status_t ccc_set (uint8_t ccc, uint8_t addr, uint8_t data)
virtual status_t ccc_get (uint8_t ccc, uint8_t addr, uint8_t *dp, uint8_t length)
Public Member Functions inherited from Obj
Obj (bool done=false)
virtual ~Obj ()
Static Public Member Functions
static void err_handling (status_t error, uint8_t address)
Public Attributes
status_t last_status
Protected Member Functions
virtual status_t write_core (uint8_t address, const uint8_t *dp, int length, bool stop=STOP)
virtual status_t read_core (uint8_t address, uint8_t *dp, int length, bool stop=STOP)
Private Attributes
lpi2c_master_config_t masterConfig
LPI2C_Type * unit_base
DigitalInOut _sda
DigitalInOut _scl
err_cb_ptr err_cb
Detailed Description
I2C class
A class for demonstrating I2C bus
Definition at line 24 of file i2c.h.
Member Typedef Documentation
err_cb_ptr
typedef void(* I2C::err_cb_ptr) (status_t status, uint8_t address)
defining pointer to NAK callback
Definition at line 29 of file i2c.h.
Member Enumeration Documentation
FREQ
enum I2C::FREQ
constants for SCL frequency settings
Enumerator
FREQ
Definition at line 39 of file i2c.h.
STOP_CONDITION
enum I2C::STOP_CONDITION
constants for STOP-cindition setting
Enumerator
STOP
NO_STOP
Definition at line 32 of file i2c.h.
Constructor & Destructor Documentation
I2C()
I2C::I2C (int sda, int scl, bool no_hw = false)
Create an I2C instance with specified pins
Parameters
sda pin number to connect SDA
scl pin number to connect SCL
no_hw (option) flag for I3C. I3C constructor will set this flag to avoid set hardware for both I3C and I2C
Definition at line 40 of file i2c.cpp.
References _scl, _sda, err_callback(), err_cb, err_handling(), masterConfig, Obj::Obj(), panic(), and unit_base.
~I2C()
I2C::~I2C () virtual
Destractor to freeing I3C resource
Definition at line 132 of file i2c.cpp.
References unit_base.
Member Function Documentation
ccc_get()
status_t I2C::ccc_get (uint8_t ccc, uint8_t addr, uint8_t * dp, uint8_t length) virtual
method for I3C class compatibility (dummy method) Does notheing but clearing data buffer and return kStatus_Success This method is for just make easy device class using I3C
Parameters
ccc CCC command
dp data to send
length data length
Returns
status_t
Reimplemented in I3C.
Definition at line 347 of file i2c.cpp.
ccc_set()
status_t I2C::ccc_set (uint8_t ccc, uint8_t addr, uint8_t data) virtual
method for I3C class compatibility (dummy method) Does notheing but return kStatus_Success This method is for just make easy device class using I3C
Parameters
ccc CCC command
data single byte data
Returns
kStatus_Success
Reimplemented in I3C.
Definition at line 342 of file i2c.cpp.
err_callback()
I2C::err_cb_ptr I2C::err_callback (err_cb_ptr callback) virtual
registering error handling method
Parameters
err_cb_ptr pointer to error handling method. use "nullptr" to suppress any actions
Definition at line 286 of file i2c.cpp.
References err_cb.
err_handling()
void I2C::err_handling (status_t error, uint8_t address) static
default error handling callback method this method will be called when I2C process got an error the callback can be installed by err_callback method
Parameters
error error status code
address target address
Definition at line 294 of file i2c.cpp.
frequency()
void I2C::frequency (uint32_t frequency) virtual
set SCL frequency
Parameters
frequency integer value in "Hz"
Definition at line 137 of file i2c.cpp.
References frequency(), and unit_base.
ping()
bool I2C::ping (uint8_t addr) virtual
ping check device returns ACK
Parameters
addr target address
Returns
true if ACKs
Reimplemented in I3C.
Definition at line 302 of file i2c.cpp.
References write_core().
pullup()
void I2C::pullup (bool enable) virtual
Pull-up enable
Parameters
enable bool for enabling internal pull-up resister
Definition at line 142 of file i2c.cpp.
References _scl, _sda, DigitalInOut::PullNone, and DigitalInOut::PullUp.
read() [1/2]
status_t I2C::read (uint8_t address, uint8_t * dp, int length, bool stop = STOP) virtual
read transactiond (multiple byte data)
Parameters
targ target address
dp data to write
length data length
stop (option) generate STOP condition: "false" to make repeated-start in next transaction
Returns
status_t
Reimplemented in I3C.
Definition at line 161 of file i2c.cpp.
References err_cb, and read_core().
read() [2/2]
uint8_t I2C::read (uint8_t targ, bool stop = STOP) virtual
read transaction (single byte data) provideds interface for register read returns a single byte data status can be checked by last_status variable
Parameters
targ target address
stop (option) generate STOP condition: "false" to make repeated-start in next transaction
Returns
data
Definition at line 277 of file i2c.cpp.
References last_status, and read().
read_core()
status_t I2C::read_core (uint8_t address, uint8_t * dp, int length, bool stop = STOP) protected virtual
Definition at line 209 of file i2c.cpp.
References unit_base.
reg_read() [1/2]
uint8_t I2C::reg_read (uint8_t targ, uint8_t reg) virtual
Register read (single byte data) provideds interface for register read returns a single byte data status can be checked by last_status variable
Parameters
targ target address
reg register address
Returns
read data
Definition at line 266 of file i2c.cpp.
References last_status, NO_STOP, read(), and write().
reg_read() [2/2]
status_t I2C::reg_read (uint8_t targ, uint8_t reg, uint8_t * dp, int length) virtual
Register read (multiple byte data) provideds interface for register read
Parameters
targ target address
reg register address
dp data to write
length data length
Returns
status_t
Definition at line 256 of file i2c.cpp.
References last_status, NO_STOP, read(), and write().
reg_write() [1/2]
status_t I2C::reg_write (uint8_t targ, uint8_t reg, const uint8_t * dp, int length) virtual
Register write (multiple byte data) provideds interface for register write
Parameters
targ target address
reg register address
dp data to write
length data length
Returns
status_t
Definition at line 234 of file i2c.cpp.
References last_status, REG_RW_BUFFER_SIZE, and write().
reg_write() [2/2]
status_t I2C::reg_write (uint8_t targ, uint8_t reg, uint8_t data) virtual
Register write (single byte data) provideds interface for register write
Parameters
targ target address
reg register address
data data to write
Returns
status_t
Definition at line 246 of file i2c.cpp.
References write().
scan() [1/3]
void I2C::scan (uint8_t last = 124) virtual
device scan device scan result will be shown on the screen scan range can be specified and last parameter
Parameters
last scan last address
Reimplemented in I3C.
Definition at line 337 of file i2c.cpp.
References scan().
scan() [2/3]
void I2C::scan (uint8_t start, uint8_t last) virtual
device scan device scan result will be shown on the screen scan range can be specified by start and last parameters
Parameters
start scan start address
last scan last address
Reimplemented in I3C.
Definition at line 314 of file i2c.cpp.
References scan().
scan() [3/3]
void I2C::scan (uint8_t start, uint8_t last, bool * result) virtual
device scan device scan result will be stored in *bool
Parameters
start scan start address
last scan last address
Reimplemented in I3C.
Definition at line 308 of file i2c.cpp.
References ping().
write() [1/2]
status_t I2C::write (uint8_t address, const uint8_t * dp, int length, bool stop = STOP) virtual
write transactiond (multiple byte data)
Parameters
targ target address
dp data to write
length data length
stop (option) generate STOP condition: "false" to make repeated-start in next transaction
Returns
status_t
Reimplemented in I3C.
Definition at line 150 of file i2c.cpp.
References err_cb, and write_core().
write() [2/2]
status_t I2C::write (uint8_t targ, uint8_t data, bool stop = STOP) virtual
write transactiond (single byte data)
Parameters
targ target address
data data to write
stop (option) generate STOP condition: "false" to make repeated-start in next transaction
Returns
status_t
Definition at line 272 of file i2c.cpp.
References write().
write_core()
status_t I2C::write_core (uint8_t address, const uint8_t * dp, int length, bool stop = STOP) protected virtual
Definition at line 172 of file i2c.cpp.
Member Data Documentation
_scl
DigitalInOut I2C::_scl private
Definition at line 231 of file i2c.h.
_sda
DigitalInOut I2C::_sda private
Definition at line 230 of file i2c.h.
err_cb
err_cb_ptr I2C::err_cb private
Definition at line 232 of file i2c.h.
last_status
status_t I2C::last_status
variable for reporting last state
Definition at line 221 of file i2c.h.
masterConfig
lpi2c_master_config_t I2C::masterConfig private
Definition at line 228 of file i2c.h.
unit_base
LPI2C_Type* I2C::unit_base private
Definition at line 229 of file i2c.h.
The documentation for this class was generated from the following files:
r01lib/i2c.h
r01lib/i2c.cpp