r01lib: GPIO_SPI Class Reference
GPIO_SPI Class Reference
#include <GPIO_SPI.h>
Public Member Functions
GPIO_SPI (SPI &interface, uint8_t device_address)
virtual ~GPIO_SPI ()
int txrx (const uint8_t *write_data, uint8_t *read_data, uint16_t size)
int reg_w (uint8_t reg_adr, const uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
void write_r16 (uint8_t reg, uint16_t val)
uint8_t read_r8 (uint8_t reg)
uint16_t read_r16 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
Public Member Functions inherited from Serial_device
Serial_device ()
virtual ~Serial_device ()
Private Attributes
SPI & spi
uint8_t dev_addr
Static Private Attributes
static constexpr uint8_t auto_increment = 0x80
Detailed Description
Definition at line 24 of file GPIO_SPI.h.
Constructor & Destructor Documentation
GPIO_SPI()
GPIO_SPI::GPIO_SPI (SPI & interface, uint8_t device_address)
Create a I2C_device instance with specified address
Parameters
interface SPI instance
device_address device address
Definition at line 9 of file GPIO_SPI.cpp.
References dev_addr, and spi.
~GPIO_SPI()
GPIO_SPI::~GPIO_SPI () virtual
Destructor of I2C_device
Definition at line 13 of file GPIO_SPI.cpp.
Member Function Documentation
bit_op16()
void GPIO_SPI::bit_op16 (uint8_t reg, uint16_t mask, uint16_t value) virtual
Reimplemented from Serial_device.
Definition at line 113 of file GPIO_SPI.cpp.
References read_r16(), and write_r16().
bit_op8()
void GPIO_SPI::bit_op8 (uint8_t reg, uint8_t mask, uint8_t value) virtual
Register overwriting with bit-mask
Register can be updated by bit level
Parameters
reg register index/address/pointer
mask bit-mask to protect overwriting
value value to overwrite
Implements Serial_device.
Definition at line 103 of file GPIO_SPI.cpp.
References read_r8(), and write_r8().
read_r16()
uint16_t GPIO_SPI::read_r16 (uint8_t reg) virtual
Register read, 16 bit
This 16 bit access may ot be common but it's useful for sensor devices
Parameters
reg register index/address/pointer
Returns
data value
Reimplemented from Serial_device.
Definition at line 94 of file GPIO_SPI.cpp.
References reg_r().
read_r8()
uint8_t GPIO_SPI::read_r8 (uint8_t reg) virtual
Register read, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
Implements Serial_device.
Definition at line 89 of file GPIO_SPI.cpp.
References reg_r().
reg_r() [1/2]
uint8_t GPIO_SPI::reg_r (uint8_t reg_adr) virtual
Single register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
read data size
Implements Serial_device.
Definition at line 60 of file GPIO_SPI.cpp.
References dev_addr, and spi.
reg_r() [2/2]
int GPIO_SPI::reg_r (uint8_t reg_adr, uint8_t * data, uint16_t size) virtual
Multiple register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Implements Serial_device.
Definition at line 45 of file GPIO_SPI.cpp.
References auto_increment, dev_addr, and spi.
reg_w() [1/2]
int GPIO_SPI::reg_w (uint8_t reg_adr, const uint8_t * data, uint16_t size) virtual
Multiple register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Implements Serial_device.
Definition at line 17 of file GPIO_SPI.cpp.
References auto_increment, dev_addr, and spi.
reg_w() [2/2]
int GPIO_SPI::reg_w (uint8_t reg_adr, uint8_t data) virtual
Single register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Implements Serial_device.
Definition at line 31 of file GPIO_SPI.cpp.
References dev_addr, and spi.
txrx()
int GPIO_SPI::txrx (const uint8_t * write_data, uint8_t * read_data, uint16_t size)
Send and receive data
Parameters
write_data pointer to write data buffer
read_data pointer to read data buffer
size data size
Returns
transferred data size or error code in negative number: -1=data too long, -2=NACK for address, -3=NACK for data, -4=Other error, -5=Time out
write_r16()
void GPIO_SPI::write_r16 (uint8_t reg, uint16_t val) virtual
Register write, 16 bit
This 16 bit access may ot be common but it's useful for sensor devices
Parameters
reg register index/address/pointer
val data value
Reimplemented from Serial_device.
Definition at line 79 of file GPIO_SPI.cpp.
References reg_w().
write_r8()
void GPIO_SPI::write_r8 (uint8_t reg, uint8_t val) virtual
Register write, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
Implements Serial_device.
Definition at line 74 of file GPIO_SPI.cpp.
References reg_w().
Member Data Documentation
auto_increment
uint8_t GPIO_SPI::auto_increment = 0x80 static constexpr private
Definition at line 129 of file GPIO_SPI.h.
dev_addr
uint8_t GPIO_SPI::dev_addr private
Definition at line 128 of file GPIO_SPI.h.
spi
SPI& GPIO_SPI::spi private
Definition at line 127 of file GPIO_SPI.h.
The documentation for this class was generated from the following files:
r01device/gpio/GPIO_SPI.h
r01device/gpio/GPIO_SPI.cpp