r01lib: r01lib/mcu.h File Reference
mcu.h File Reference
#include "r01lib.h"
Functions
void init_mcu (void)
void wait (double delayTime_sec)
void wait_ms (unsigned int milloseconds)
void wait_us (unsigned int microseconds)
void panic (const char *s)
Function Documentation
init_mcu()
void init_mcu (void)
Definition at line 41 of file mcu.cpp.
panic()
void panic (const char * s)
Definition at line 202 of file mcu.cpp.
References wait().
wait()
void wait (double delayTime_sec)
Definition at line 187 of file mcu.cpp.
wait_ms()
void wait_ms (unsigned int milloseconds)
Definition at line 192 of file mcu.cpp.
References wait().
wait_us()
void wait_us (unsigned int microseconds)
Definition at line 197 of file mcu.cpp.
References wait().